// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/collaborationdevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationDevice is the model entity for the CollaborationDevice schema.
type CollaborationDevice struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// InstallationIDHash holds the value of the "installation_id_hash" field.
	InstallationIDHash string `json:"installation_id_hash,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform collaborationdevice.Platform `json:"platform,omitempty"`
	// PlatformVersion holds the value of the "platform_version" field.
	PlatformVersion *string `json:"platform_version,omitempty"`
	// CompanionVersion holds the value of the "companion_version" field.
	CompanionVersion string `json:"companion_version,omitempty"`
	// CodexVersion holds the value of the "codex_version" field.
	CodexVersion *string `json:"codex_version,omitempty"`
	// ProtocolVersion holds the value of the "protocol_version" field.
	ProtocolVersion int `json:"protocol_version,omitempty"`
	// Status holds the value of the "status" field.
	Status collaborationdevice.Status `json:"status,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// RegisteredAt holds the value of the "registered_at" field.
	RegisteredAt time.Time `json:"registered_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollaborationDeviceQuery when eager-loading is set.
	Edges        CollaborationDeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CollaborationDeviceEdges holds the relations/edges for other nodes in the graph.
type CollaborationDeviceEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// SyncRequests holds the value of the sync_requests edge.
	SyncRequests []*CollaborationSyncRequest `json:"sync_requests,omitempty"`
	// Commands holds the value of the commands edge.
	Commands []*CollaborationCommand `json:"commands,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationDeviceEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SyncRequestsOrErr returns the SyncRequests value or an error if the edge
// was not loaded in eager-loading.
func (e CollaborationDeviceEdges) SyncRequestsOrErr() ([]*CollaborationSyncRequest, error) {
	if e.loadedTypes[1] {
		return e.SyncRequests, nil
	}
	return nil, &NotLoadedError{edge: "sync_requests"}
}

// CommandsOrErr returns the Commands value or an error if the edge
// was not loaded in eager-loading.
func (e CollaborationDeviceEdges) CommandsOrErr() ([]*CollaborationCommand, error) {
	if e.loadedTypes[2] {
		return e.Commands, nil
	}
	return nil, &NotLoadedError{edge: "commands"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CollaborationDevice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collaborationdevice.FieldCapabilities:
			values[i] = new([]byte)
		case collaborationdevice.FieldUserID, collaborationdevice.FieldProtocolVersion:
			values[i] = new(sql.NullInt64)
		case collaborationdevice.FieldInstallationIDHash, collaborationdevice.FieldName, collaborationdevice.FieldPlatform, collaborationdevice.FieldPlatformVersion, collaborationdevice.FieldCompanionVersion, collaborationdevice.FieldCodexVersion, collaborationdevice.FieldStatus:
			values[i] = new(sql.NullString)
		case collaborationdevice.FieldCreatedAt, collaborationdevice.FieldUpdatedAt, collaborationdevice.FieldLastSeenAt, collaborationdevice.FieldRevokedAt, collaborationdevice.FieldRegisteredAt:
			values[i] = new(sql.NullTime)
		case collaborationdevice.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CollaborationDevice fields.
func (_m *CollaborationDevice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collaborationdevice.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case collaborationdevice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case collaborationdevice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case collaborationdevice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case collaborationdevice.FieldInstallationIDHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id_hash", values[i])
			} else if value.Valid {
				_m.InstallationIDHash = value.String
			}
		case collaborationdevice.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case collaborationdevice.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = collaborationdevice.Platform(value.String)
			}
		case collaborationdevice.FieldPlatformVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_version", values[i])
			} else if value.Valid {
				_m.PlatformVersion = new(string)
				*_m.PlatformVersion = value.String
			}
		case collaborationdevice.FieldCompanionVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field companion_version", values[i])
			} else if value.Valid {
				_m.CompanionVersion = value.String
			}
		case collaborationdevice.FieldCodexVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field codex_version", values[i])
			} else if value.Valid {
				_m.CodexVersion = new(string)
				*_m.CodexVersion = value.String
			}
		case collaborationdevice.FieldProtocolVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field protocol_version", values[i])
			} else if value.Valid {
				_m.ProtocolVersion = int(value.Int64)
			}
		case collaborationdevice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = collaborationdevice.Status(value.String)
			}
		case collaborationdevice.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case collaborationdevice.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		case collaborationdevice.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case collaborationdevice.FieldRegisteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field registered_at", values[i])
			} else if value.Valid {
				_m.RegisteredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CollaborationDevice.
// This includes values selected through modifiers, order, etc.
func (_m *CollaborationDevice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CollaborationDevice entity.
func (_m *CollaborationDevice) QueryUser() *UserQuery {
	return NewCollaborationDeviceClient(_m.config).QueryUser(_m)
}

// QuerySyncRequests queries the "sync_requests" edge of the CollaborationDevice entity.
func (_m *CollaborationDevice) QuerySyncRequests() *CollaborationSyncRequestQuery {
	return NewCollaborationDeviceClient(_m.config).QuerySyncRequests(_m)
}

// QueryCommands queries the "commands" edge of the CollaborationDevice entity.
func (_m *CollaborationDevice) QueryCommands() *CollaborationCommandQuery {
	return NewCollaborationDeviceClient(_m.config).QueryCommands(_m)
}

// Update returns a builder for updating this CollaborationDevice.
// Note that you need to call CollaborationDevice.Unwrap() before calling this method if this CollaborationDevice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CollaborationDevice) Update() *CollaborationDeviceUpdateOne {
	return NewCollaborationDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CollaborationDevice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CollaborationDevice) Unwrap() *CollaborationDevice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CollaborationDevice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CollaborationDevice) String() string {
	var builder strings.Builder
	builder.WriteString("CollaborationDevice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("installation_id_hash=")
	builder.WriteString(_m.InstallationIDHash)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	if v := _m.PlatformVersion; v != nil {
		builder.WriteString("platform_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("companion_version=")
	builder.WriteString(_m.CompanionVersion)
	builder.WriteString(", ")
	if v := _m.CodexVersion; v != nil {
		builder.WriteString("codex_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("protocol_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProtocolVersion))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("registered_at=")
	builder.WriteString(_m.RegisteredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CollaborationDevices is a parsable slice of CollaborationDevice.
type CollaborationDevices []*CollaborationDevice
