// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CollaborationChargeDelete is the builder for deleting a CollaborationCharge entity.
type CollaborationChargeDelete struct {
	config
	hooks    []Hook
	mutation *CollaborationChargeMutation
}

// Where appends a list predicates to the CollaborationChargeDelete builder.
func (_d *CollaborationChargeDelete) Where(ps ...predicate.CollaborationCharge) *CollaborationChargeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CollaborationChargeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationChargeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CollaborationChargeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(collaborationcharge.Table, sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CollaborationChargeDeleteOne is the builder for deleting a single CollaborationCharge entity.
type CollaborationChargeDeleteOne struct {
	_d *CollaborationChargeDelete
}

// Where appends a list predicates to the CollaborationChargeDelete builder.
func (_d *CollaborationChargeDeleteOne) Where(ps ...predicate.CollaborationCharge) *CollaborationChargeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CollaborationChargeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{collaborationcharge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationChargeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
