// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationsyncrequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CollaborationSyncRequestDelete is the builder for deleting a CollaborationSyncRequest entity.
type CollaborationSyncRequestDelete struct {
	config
	hooks    []Hook
	mutation *CollaborationSyncRequestMutation
}

// Where appends a list predicates to the CollaborationSyncRequestDelete builder.
func (_d *CollaborationSyncRequestDelete) Where(ps ...predicate.CollaborationSyncRequest) *CollaborationSyncRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CollaborationSyncRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationSyncRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CollaborationSyncRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(collaborationsyncrequest.Table, sqlgraph.NewFieldSpec(collaborationsyncrequest.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CollaborationSyncRequestDeleteOne is the builder for deleting a single CollaborationSyncRequest entity.
type CollaborationSyncRequestDeleteOne struct {
	_d *CollaborationSyncRequestDelete
}

// Where appends a list predicates to the CollaborationSyncRequestDelete builder.
func (_d *CollaborationSyncRequestDeleteOne) Where(ps ...predicate.CollaborationSyncRequest) *CollaborationSyncRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CollaborationSyncRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{collaborationsyncrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationSyncRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
