// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationCharge is the model entity for the CollaborationCharge schema.
type CollaborationCharge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CommandID holds the value of the "command_id" field.
	CommandID uuid.UUID `json:"command_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount string `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status collaborationcharge.Status `json:"status,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore string `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter string `json:"balance_after,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// ChargedAt holds the value of the "charged_at" field.
	ChargedAt time.Time `json:"charged_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollaborationChargeQuery when eager-loading is set.
	Edges        CollaborationChargeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CollaborationChargeEdges holds the relations/edges for other nodes in the graph.
type CollaborationChargeEdges struct {
	// Command holds the value of the command edge.
	Command *CollaborationCommand `json:"command,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CommandOrErr returns the Command value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationChargeEdges) CommandOrErr() (*CollaborationCommand, error) {
	if e.Command != nil {
		return e.Command, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: collaborationcommand.Label}
	}
	return nil, &NotLoadedError{edge: "command"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationChargeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CollaborationCharge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collaborationcharge.FieldUserID:
			values[i] = new(sql.NullInt64)
		case collaborationcharge.FieldAmount, collaborationcharge.FieldCurrency, collaborationcharge.FieldStatus, collaborationcharge.FieldBalanceBefore, collaborationcharge.FieldBalanceAfter, collaborationcharge.FieldReason:
			values[i] = new(sql.NullString)
		case collaborationcharge.FieldChargedAt:
			values[i] = new(sql.NullTime)
		case collaborationcharge.FieldID, collaborationcharge.FieldCommandID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CollaborationCharge fields.
func (_m *CollaborationCharge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collaborationcharge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case collaborationcharge.FieldCommandID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field command_id", values[i])
			} else if value != nil {
				_m.CommandID = *value
			}
		case collaborationcharge.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case collaborationcharge.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.String
			}
		case collaborationcharge.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case collaborationcharge.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = collaborationcharge.Status(value.String)
			}
		case collaborationcharge.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.String
			}
		case collaborationcharge.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.String
			}
		case collaborationcharge.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case collaborationcharge.FieldChargedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field charged_at", values[i])
			} else if value.Valid {
				_m.ChargedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CollaborationCharge.
// This includes values selected through modifiers, order, etc.
func (_m *CollaborationCharge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCommand queries the "command" edge of the CollaborationCharge entity.
func (_m *CollaborationCharge) QueryCommand() *CollaborationCommandQuery {
	return NewCollaborationChargeClient(_m.config).QueryCommand(_m)
}

// QueryUser queries the "user" edge of the CollaborationCharge entity.
func (_m *CollaborationCharge) QueryUser() *UserQuery {
	return NewCollaborationChargeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CollaborationCharge.
// Note that you need to call CollaborationCharge.Unwrap() before calling this method if this CollaborationCharge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CollaborationCharge) Update() *CollaborationChargeUpdateOne {
	return NewCollaborationChargeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CollaborationCharge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CollaborationCharge) Unwrap() *CollaborationCharge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CollaborationCharge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CollaborationCharge) String() string {
	var builder strings.Builder
	builder.WriteString("CollaborationCharge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("command_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommandID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(_m.Amount)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(_m.BalanceBefore)
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(_m.BalanceAfter)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("charged_at=")
	builder.WriteString(_m.ChargedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CollaborationCharges is a parsable slice of CollaborationCharge.
type CollaborationCharges []*CollaborationCharge
