// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationdevice"
	"github.com/Wei-Shaw/sub2api/ent/collaborationsyncrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationSyncRequestCreate is the builder for creating a CollaborationSyncRequest entity.
type CollaborationSyncRequestCreate struct {
	config
	mutation *CollaborationSyncRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CollaborationSyncRequestCreate) SetCreatedAt(v time.Time) *CollaborationSyncRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableCreatedAt(v *time.Time) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CollaborationSyncRequestCreate) SetUpdatedAt(v time.Time) *CollaborationSyncRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableUpdatedAt(v *time.Time) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CollaborationSyncRequestCreate) SetUserID(v int64) *CollaborationSyncRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *CollaborationSyncRequestCreate) SetDeviceID(v uuid.UUID) *CollaborationSyncRequestCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *CollaborationSyncRequestCreate) SetIdempotencyKey(v uuid.UUID) *CollaborationSyncRequestCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *CollaborationSyncRequestCreate) SetKind(v collaborationsyncrequest.Kind) *CollaborationSyncRequestCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetThreadID sets the "thread_id" field.
func (_c *CollaborationSyncRequestCreate) SetThreadID(v string) *CollaborationSyncRequestCreate {
	_c.mutation.SetThreadID(v)
	return _c
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableThreadID(v *string) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetThreadID(*v)
	}
	return _c
}

// SetCursor sets the "cursor" field.
func (_c *CollaborationSyncRequestCreate) SetCursor(v string) *CollaborationSyncRequestCreate {
	_c.mutation.SetCursor(v)
	return _c
}

// SetNillableCursor sets the "cursor" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableCursor(v *string) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetCursor(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CollaborationSyncRequestCreate) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableStatus(v *collaborationsyncrequest.Status) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *CollaborationSyncRequestCreate) SetErrorCode(v string) *CollaborationSyncRequestCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableErrorCode(v *string) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (_c *CollaborationSyncRequestCreate) SetSnapshotVersion(v int64) *CollaborationSyncRequestCreate {
	_c.mutation.SetSnapshotVersion(v)
	return _c
}

// SetNillableSnapshotVersion sets the "snapshot_version" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableSnapshotVersion(v *int64) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetSnapshotVersion(*v)
	}
	return _c
}

// SetResultCount sets the "result_count" field.
func (_c *CollaborationSyncRequestCreate) SetResultCount(v int) *CollaborationSyncRequestCreate {
	_c.mutation.SetResultCount(v)
	return _c
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableResultCount(v *int) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetResultCount(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CollaborationSyncRequestCreate) SetExpiresAt(v time.Time) *CollaborationSyncRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *CollaborationSyncRequestCreate) SetCompletedAt(v time.Time) *CollaborationSyncRequestCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableCompletedAt(v *time.Time) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CollaborationSyncRequestCreate) SetID(v uuid.UUID) *CollaborationSyncRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CollaborationSyncRequestCreate) SetNillableID(v *uuid.UUID) *CollaborationSyncRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CollaborationSyncRequestCreate) SetUser(v *User) *CollaborationSyncRequestCreate {
	return _c.SetUserID(v.ID)
}

// SetDevice sets the "device" edge to the CollaborationDevice entity.
func (_c *CollaborationSyncRequestCreate) SetDevice(v *CollaborationDevice) *CollaborationSyncRequestCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the CollaborationSyncRequestMutation object of the builder.
func (_c *CollaborationSyncRequestCreate) Mutation() *CollaborationSyncRequestMutation {
	return _c.mutation
}

// Save creates the CollaborationSyncRequest in the database.
func (_c *CollaborationSyncRequestCreate) Save(ctx context.Context) (*CollaborationSyncRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CollaborationSyncRequestCreate) SaveX(ctx context.Context) *CollaborationSyncRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationSyncRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationSyncRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CollaborationSyncRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := collaborationsyncrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := collaborationsyncrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := collaborationsyncrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		v := collaborationsyncrequest.DefaultResultCount
		_c.mutation.SetResultCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := collaborationsyncrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CollaborationSyncRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CollaborationSyncRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CollaborationSyncRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CollaborationSyncRequest.user_id"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "CollaborationSyncRequest.device_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "CollaborationSyncRequest.idempotency_key"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "CollaborationSyncRequest.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := collaborationsyncrequest.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ThreadID(); ok {
		if err := collaborationsyncrequest.ThreadIDValidator(v); err != nil {
			return &ValidationError{Name: "thread_id", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.thread_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Cursor(); ok {
		if err := collaborationsyncrequest.CursorValidator(v); err != nil {
			return &ValidationError{Name: "cursor", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.cursor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CollaborationSyncRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := collaborationsyncrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := collaborationsyncrequest.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		return &ValidationError{Name: "result_count", err: errors.New(`ent: missing required field "CollaborationSyncRequest.result_count"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CollaborationSyncRequest.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CollaborationSyncRequest.user"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "CollaborationSyncRequest.device"`)}
	}
	return nil
}

func (_c *CollaborationSyncRequestCreate) sqlSave(ctx context.Context) (*CollaborationSyncRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CollaborationSyncRequestCreate) createSpec() (*CollaborationSyncRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &CollaborationSyncRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(collaborationsyncrequest.Table, sqlgraph.NewFieldSpec(collaborationsyncrequest.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(collaborationsyncrequest.FieldIdempotencyKey, field.TypeUUID, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(collaborationsyncrequest.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ThreadID(); ok {
		_spec.SetField(collaborationsyncrequest.FieldThreadID, field.TypeString, value)
		_node.ThreadID = &value
	}
	if value, ok := _c.mutation.Cursor(); ok {
		_spec.SetField(collaborationsyncrequest.FieldCursor, field.TypeString, value)
		_node.Cursor = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(collaborationsyncrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(collaborationsyncrequest.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.SnapshotVersion(); ok {
		_spec.SetField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64, value)
		_node.SnapshotVersion = &value
	}
	if value, ok := _c.mutation.ResultCount(); ok {
		_spec.SetField(collaborationsyncrequest.FieldResultCount, field.TypeInt, value)
		_node.ResultCount = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collaborationsyncrequest.UserTable,
			Columns: []string{collaborationsyncrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collaborationsyncrequest.DeviceTable,
			Columns: []string{collaborationsyncrequest.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationdevice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationSyncRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationSyncRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationSyncRequestCreate) OnConflict(opts ...sql.ConflictOption) *CollaborationSyncRequestUpsertOne {
	_c.conflict = opts
	return &CollaborationSyncRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationSyncRequestCreate) OnConflictColumns(columns ...string) *CollaborationSyncRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationSyncRequestUpsertOne{
		create: _c,
	}
}

type (
	// CollaborationSyncRequestUpsertOne is the builder for "upsert"-ing
	//  one CollaborationSyncRequest node.
	CollaborationSyncRequestUpsertOne struct {
		create *CollaborationSyncRequestCreate
	}

	// CollaborationSyncRequestUpsert is the "OnConflict" setter.
	CollaborationSyncRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationSyncRequestUpsert) SetUpdatedAt(v time.Time) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateUpdatedAt() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *CollaborationSyncRequestUpsert) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateStatus() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldStatus)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *CollaborationSyncRequestUpsert) SetErrorCode(v string) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateErrorCode() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *CollaborationSyncRequestUpsert) ClearErrorCode() *CollaborationSyncRequestUpsert {
	u.SetNull(collaborationsyncrequest.FieldErrorCode)
	return u
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsert) SetSnapshotVersion(v int64) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldSnapshotVersion, v)
	return u
}

// UpdateSnapshotVersion sets the "snapshot_version" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateSnapshotVersion() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldSnapshotVersion)
	return u
}

// AddSnapshotVersion adds v to the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsert) AddSnapshotVersion(v int64) *CollaborationSyncRequestUpsert {
	u.Add(collaborationsyncrequest.FieldSnapshotVersion, v)
	return u
}

// ClearSnapshotVersion clears the value of the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsert) ClearSnapshotVersion() *CollaborationSyncRequestUpsert {
	u.SetNull(collaborationsyncrequest.FieldSnapshotVersion)
	return u
}

// SetResultCount sets the "result_count" field.
func (u *CollaborationSyncRequestUpsert) SetResultCount(v int) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldResultCount, v)
	return u
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateResultCount() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldResultCount)
	return u
}

// AddResultCount adds v to the "result_count" field.
func (u *CollaborationSyncRequestUpsert) AddResultCount(v int) *CollaborationSyncRequestUpsert {
	u.Add(collaborationsyncrequest.FieldResultCount, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CollaborationSyncRequestUpsert) SetExpiresAt(v time.Time) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateExpiresAt() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldExpiresAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *CollaborationSyncRequestUpsert) SetCompletedAt(v time.Time) *CollaborationSyncRequestUpsert {
	u.Set(collaborationsyncrequest.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsert) UpdateCompletedAt() *CollaborationSyncRequestUpsert {
	u.SetExcluded(collaborationsyncrequest.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CollaborationSyncRequestUpsert) ClearCompletedAt() *CollaborationSyncRequestUpsert {
	u.SetNull(collaborationsyncrequest.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationsyncrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationSyncRequestUpsertOne) UpdateNewValues() *CollaborationSyncRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldUserID)
		}
		if _, exists := u.create.mutation.DeviceID(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldDeviceID)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldKind)
		}
		if _, exists := u.create.mutation.ThreadID(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldThreadID)
		}
		if _, exists := u.create.mutation.Cursor(); exists {
			s.SetIgnore(collaborationsyncrequest.FieldCursor)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CollaborationSyncRequestUpsertOne) Ignore() *CollaborationSyncRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationSyncRequestUpsertOne) DoNothing() *CollaborationSyncRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationSyncRequestCreate.OnConflict
// documentation for more info.
func (u *CollaborationSyncRequestUpsertOne) Update(set func(*CollaborationSyncRequestUpsert)) *CollaborationSyncRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationSyncRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationSyncRequestUpsertOne) SetUpdatedAt(v time.Time) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateUpdatedAt() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *CollaborationSyncRequestUpsertOne) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateStatus() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *CollaborationSyncRequestUpsertOne) SetErrorCode(v string) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateErrorCode() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *CollaborationSyncRequestUpsertOne) ClearErrorCode() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearErrorCode()
	})
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertOne) SetSnapshotVersion(v int64) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetSnapshotVersion(v)
	})
}

// AddSnapshotVersion adds v to the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertOne) AddSnapshotVersion(v int64) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.AddSnapshotVersion(v)
	})
}

// UpdateSnapshotVersion sets the "snapshot_version" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateSnapshotVersion() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateSnapshotVersion()
	})
}

// ClearSnapshotVersion clears the value of the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertOne) ClearSnapshotVersion() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearSnapshotVersion()
	})
}

// SetResultCount sets the "result_count" field.
func (u *CollaborationSyncRequestUpsertOne) SetResultCount(v int) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *CollaborationSyncRequestUpsertOne) AddResultCount(v int) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateResultCount() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateResultCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CollaborationSyncRequestUpsertOne) SetExpiresAt(v time.Time) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateExpiresAt() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CollaborationSyncRequestUpsertOne) SetCompletedAt(v time.Time) *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertOne) UpdateCompletedAt() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CollaborationSyncRequestUpsertOne) ClearCompletedAt() *CollaborationSyncRequestUpsertOne {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *CollaborationSyncRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationSyncRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationSyncRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CollaborationSyncRequestUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CollaborationSyncRequestUpsertOne.ID is not supported by MySQL driver. Use CollaborationSyncRequestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CollaborationSyncRequestUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CollaborationSyncRequestCreateBulk is the builder for creating many CollaborationSyncRequest entities in bulk.
type CollaborationSyncRequestCreateBulk struct {
	config
	err      error
	builders []*CollaborationSyncRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the CollaborationSyncRequest entities in the database.
func (_c *CollaborationSyncRequestCreateBulk) Save(ctx context.Context) ([]*CollaborationSyncRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CollaborationSyncRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CollaborationSyncRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CollaborationSyncRequestCreateBulk) SaveX(ctx context.Context) []*CollaborationSyncRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationSyncRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationSyncRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationSyncRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationSyncRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationSyncRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *CollaborationSyncRequestUpsertBulk {
	_c.conflict = opts
	return &CollaborationSyncRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationSyncRequestCreateBulk) OnConflictColumns(columns ...string) *CollaborationSyncRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationSyncRequestUpsertBulk{
		create: _c,
	}
}

// CollaborationSyncRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of CollaborationSyncRequest nodes.
type CollaborationSyncRequestUpsertBulk struct {
	create *CollaborationSyncRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationsyncrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationSyncRequestUpsertBulk) UpdateNewValues() *CollaborationSyncRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldUserID)
			}
			if _, exists := b.mutation.DeviceID(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldDeviceID)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldKind)
			}
			if _, exists := b.mutation.ThreadID(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldThreadID)
			}
			if _, exists := b.mutation.Cursor(); exists {
				s.SetIgnore(collaborationsyncrequest.FieldCursor)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationSyncRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CollaborationSyncRequestUpsertBulk) Ignore() *CollaborationSyncRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationSyncRequestUpsertBulk) DoNothing() *CollaborationSyncRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationSyncRequestCreateBulk.OnConflict
// documentation for more info.
func (u *CollaborationSyncRequestUpsertBulk) Update(set func(*CollaborationSyncRequestUpsert)) *CollaborationSyncRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationSyncRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationSyncRequestUpsertBulk) SetUpdatedAt(v time.Time) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateUpdatedAt() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *CollaborationSyncRequestUpsertBulk) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateStatus() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *CollaborationSyncRequestUpsertBulk) SetErrorCode(v string) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateErrorCode() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *CollaborationSyncRequestUpsertBulk) ClearErrorCode() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearErrorCode()
	})
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertBulk) SetSnapshotVersion(v int64) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetSnapshotVersion(v)
	})
}

// AddSnapshotVersion adds v to the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertBulk) AddSnapshotVersion(v int64) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.AddSnapshotVersion(v)
	})
}

// UpdateSnapshotVersion sets the "snapshot_version" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateSnapshotVersion() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateSnapshotVersion()
	})
}

// ClearSnapshotVersion clears the value of the "snapshot_version" field.
func (u *CollaborationSyncRequestUpsertBulk) ClearSnapshotVersion() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearSnapshotVersion()
	})
}

// SetResultCount sets the "result_count" field.
func (u *CollaborationSyncRequestUpsertBulk) SetResultCount(v int) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *CollaborationSyncRequestUpsertBulk) AddResultCount(v int) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateResultCount() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateResultCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CollaborationSyncRequestUpsertBulk) SetExpiresAt(v time.Time) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateExpiresAt() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CollaborationSyncRequestUpsertBulk) SetCompletedAt(v time.Time) *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CollaborationSyncRequestUpsertBulk) UpdateCompletedAt() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *CollaborationSyncRequestUpsertBulk) ClearCompletedAt() *CollaborationSyncRequestUpsertBulk {
	return u.Update(func(s *CollaborationSyncRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *CollaborationSyncRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CollaborationSyncRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationSyncRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationSyncRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
