// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/collaborationdevice"
	"github.com/Wei-Shaw/sub2api/ent/collaborationsyncrequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationDeviceQuery is the builder for querying CollaborationDevice entities.
type CollaborationDeviceQuery struct {
	config
	ctx              *QueryContext
	order            []collaborationdevice.OrderOption
	inters           []Interceptor
	predicates       []predicate.CollaborationDevice
	withUser         *UserQuery
	withSyncRequests *CollaborationSyncRequestQuery
	withCommands     *CollaborationCommandQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CollaborationDeviceQuery builder.
func (_q *CollaborationDeviceQuery) Where(ps ...predicate.CollaborationDevice) *CollaborationDeviceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CollaborationDeviceQuery) Limit(limit int) *CollaborationDeviceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CollaborationDeviceQuery) Offset(offset int) *CollaborationDeviceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CollaborationDeviceQuery) Unique(unique bool) *CollaborationDeviceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CollaborationDeviceQuery) Order(o ...collaborationdevice.OrderOption) *CollaborationDeviceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *CollaborationDeviceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(collaborationdevice.Table, collaborationdevice.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, collaborationdevice.UserTable, collaborationdevice.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySyncRequests chains the current query on the "sync_requests" edge.
func (_q *CollaborationDeviceQuery) QuerySyncRequests() *CollaborationSyncRequestQuery {
	query := (&CollaborationSyncRequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(collaborationdevice.Table, collaborationdevice.FieldID, selector),
			sqlgraph.To(collaborationsyncrequest.Table, collaborationsyncrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, collaborationdevice.SyncRequestsTable, collaborationdevice.SyncRequestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommands chains the current query on the "commands" edge.
func (_q *CollaborationDeviceQuery) QueryCommands() *CollaborationCommandQuery {
	query := (&CollaborationCommandClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(collaborationdevice.Table, collaborationdevice.FieldID, selector),
			sqlgraph.To(collaborationcommand.Table, collaborationcommand.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, collaborationdevice.CommandsTable, collaborationdevice.CommandsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CollaborationDevice entity from the query.
// Returns a *NotFoundError when no CollaborationDevice was found.
func (_q *CollaborationDeviceQuery) First(ctx context.Context) (*CollaborationDevice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{collaborationdevice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) FirstX(ctx context.Context) *CollaborationDevice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CollaborationDevice ID from the query.
// Returns a *NotFoundError when no CollaborationDevice ID was found.
func (_q *CollaborationDeviceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{collaborationdevice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CollaborationDevice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CollaborationDevice entity is found.
// Returns a *NotFoundError when no CollaborationDevice entities are found.
func (_q *CollaborationDeviceQuery) Only(ctx context.Context) (*CollaborationDevice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{collaborationdevice.Label}
	default:
		return nil, &NotSingularError{collaborationdevice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) OnlyX(ctx context.Context) *CollaborationDevice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CollaborationDevice ID in the query.
// Returns a *NotSingularError when more than one CollaborationDevice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CollaborationDeviceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{collaborationdevice.Label}
	default:
		err = &NotSingularError{collaborationdevice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CollaborationDevices.
func (_q *CollaborationDeviceQuery) All(ctx context.Context) ([]*CollaborationDevice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CollaborationDevice, *CollaborationDeviceQuery]()
	return withInterceptors[[]*CollaborationDevice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) AllX(ctx context.Context) []*CollaborationDevice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CollaborationDevice IDs.
func (_q *CollaborationDeviceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(collaborationdevice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CollaborationDeviceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CollaborationDeviceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CollaborationDeviceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CollaborationDeviceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CollaborationDeviceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CollaborationDeviceQuery) Clone() *CollaborationDeviceQuery {
	if _q == nil {
		return nil
	}
	return &CollaborationDeviceQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]collaborationdevice.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.CollaborationDevice{}, _q.predicates...),
		withUser:         _q.withUser.Clone(),
		withSyncRequests: _q.withSyncRequests.Clone(),
		withCommands:     _q.withCommands.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CollaborationDeviceQuery) WithUser(opts ...func(*UserQuery)) *CollaborationDeviceQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithSyncRequests tells the query-builder to eager-load the nodes that are connected to
// the "sync_requests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CollaborationDeviceQuery) WithSyncRequests(opts ...func(*CollaborationSyncRequestQuery)) *CollaborationDeviceQuery {
	query := (&CollaborationSyncRequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSyncRequests = query
	return _q
}

// WithCommands tells the query-builder to eager-load the nodes that are connected to
// the "commands" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CollaborationDeviceQuery) WithCommands(opts ...func(*CollaborationCommandQuery)) *CollaborationDeviceQuery {
	query := (&CollaborationCommandClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCommands = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CollaborationDevice.Query().
//		GroupBy(collaborationdevice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CollaborationDeviceQuery) GroupBy(field string, fields ...string) *CollaborationDeviceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CollaborationDeviceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = collaborationdevice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CollaborationDevice.Query().
//		Select(collaborationdevice.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CollaborationDeviceQuery) Select(fields ...string) *CollaborationDeviceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CollaborationDeviceSelect{CollaborationDeviceQuery: _q}
	sbuild.label = collaborationdevice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CollaborationDeviceSelect configured with the given aggregations.
func (_q *CollaborationDeviceQuery) Aggregate(fns ...AggregateFunc) *CollaborationDeviceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CollaborationDeviceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !collaborationdevice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CollaborationDeviceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CollaborationDevice, error) {
	var (
		nodes       = []*CollaborationDevice{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withSyncRequests != nil,
			_q.withCommands != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CollaborationDevice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CollaborationDevice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CollaborationDevice, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSyncRequests; query != nil {
		if err := _q.loadSyncRequests(ctx, query, nodes,
			func(n *CollaborationDevice) { n.Edges.SyncRequests = []*CollaborationSyncRequest{} },
			func(n *CollaborationDevice, e *CollaborationSyncRequest) {
				n.Edges.SyncRequests = append(n.Edges.SyncRequests, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withCommands; query != nil {
		if err := _q.loadCommands(ctx, query, nodes,
			func(n *CollaborationDevice) { n.Edges.Commands = []*CollaborationCommand{} },
			func(n *CollaborationDevice, e *CollaborationCommand) { n.Edges.Commands = append(n.Edges.Commands, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CollaborationDeviceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CollaborationDevice, init func(*CollaborationDevice), assign func(*CollaborationDevice, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CollaborationDevice)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CollaborationDeviceQuery) loadSyncRequests(ctx context.Context, query *CollaborationSyncRequestQuery, nodes []*CollaborationDevice, init func(*CollaborationDevice), assign func(*CollaborationDevice, *CollaborationSyncRequest)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*CollaborationDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(collaborationsyncrequest.FieldDeviceID)
	}
	query.Where(predicate.CollaborationSyncRequest(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(collaborationdevice.SyncRequestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CollaborationDeviceQuery) loadCommands(ctx context.Context, query *CollaborationCommandQuery, nodes []*CollaborationDevice, init func(*CollaborationDevice), assign func(*CollaborationDevice, *CollaborationCommand)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*CollaborationDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(collaborationcommand.FieldDeviceID)
	}
	query.Where(predicate.CollaborationCommand(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(collaborationdevice.CommandsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CollaborationDeviceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CollaborationDeviceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(collaborationdevice.Table, collaborationdevice.Columns, sqlgraph.NewFieldSpec(collaborationdevice.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collaborationdevice.FieldID)
		for i := range fields {
			if fields[i] != collaborationdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(collaborationdevice.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CollaborationDeviceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(collaborationdevice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = collaborationdevice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CollaborationDeviceQuery) ForUpdate(opts ...sql.LockOption) *CollaborationDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CollaborationDeviceQuery) ForShare(opts ...sql.LockOption) *CollaborationDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CollaborationDeviceGroupBy is the group-by builder for CollaborationDevice entities.
type CollaborationDeviceGroupBy struct {
	selector
	build *CollaborationDeviceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CollaborationDeviceGroupBy) Aggregate(fns ...AggregateFunc) *CollaborationDeviceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CollaborationDeviceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollaborationDeviceQuery, *CollaborationDeviceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CollaborationDeviceGroupBy) sqlScan(ctx context.Context, root *CollaborationDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CollaborationDeviceSelect is the builder for selecting fields of CollaborationDevice entities.
type CollaborationDeviceSelect struct {
	*CollaborationDeviceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CollaborationDeviceSelect) Aggregate(fns ...AggregateFunc) *CollaborationDeviceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CollaborationDeviceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollaborationDeviceQuery, *CollaborationDeviceSelect](ctx, _s.CollaborationDeviceQuery, _s, _s.inters, v)
}

func (_s *CollaborationDeviceSelect) sqlScan(ctx context.Context, root *CollaborationDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
