// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/collaborationdevice"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationCommand is the model entity for the CollaborationCommand schema.
type CollaborationCommand struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID uuid.UUID `json:"device_id,omitempty"`
	// ThreadID holds the value of the "thread_id" field.
	ThreadID string `json:"thread_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey uuid.UUID `json:"idempotency_key,omitempty"`
	// PromptSha256 holds the value of the "prompt_sha256" field.
	PromptSha256 string `json:"prompt_sha256,omitempty"`
	// PromptBytes holds the value of the "prompt_bytes" field.
	PromptBytes int `json:"prompt_bytes,omitempty"`
	// Status holds the value of the "status" field.
	Status collaborationcommand.Status `json:"status,omitempty"`
	// TurnID holds the value of the "turn_id" field.
	TurnID *string `json:"turn_id,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// DispatchedAt holds the value of the "dispatched_at" field.
	DispatchedAt *time.Time `json:"dispatched_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollaborationCommandQuery when eager-loading is set.
	Edges        CollaborationCommandEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CollaborationCommandEdges holds the relations/edges for other nodes in the graph.
type CollaborationCommandEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Device holds the value of the device edge.
	Device *CollaborationDevice `json:"device,omitempty"`
	// Charge holds the value of the charge edge.
	Charge *CollaborationCharge `json:"charge,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationCommandEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationCommandEdges) DeviceOrErr() (*CollaborationDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: collaborationdevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// ChargeOrErr returns the Charge value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollaborationCommandEdges) ChargeOrErr() (*CollaborationCharge, error) {
	if e.Charge != nil {
		return e.Charge, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: collaborationcharge.Label}
	}
	return nil, &NotLoadedError{edge: "charge"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CollaborationCommand) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collaborationcommand.FieldUserID, collaborationcommand.FieldPromptBytes:
			values[i] = new(sql.NullInt64)
		case collaborationcommand.FieldThreadID, collaborationcommand.FieldPromptSha256, collaborationcommand.FieldStatus, collaborationcommand.FieldTurnID, collaborationcommand.FieldErrorCode:
			values[i] = new(sql.NullString)
		case collaborationcommand.FieldCreatedAt, collaborationcommand.FieldUpdatedAt, collaborationcommand.FieldExpiresAt, collaborationcommand.FieldDispatchedAt, collaborationcommand.FieldStartedAt, collaborationcommand.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case collaborationcommand.FieldID, collaborationcommand.FieldDeviceID, collaborationcommand.FieldIdempotencyKey:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CollaborationCommand fields.
func (_m *CollaborationCommand) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collaborationcommand.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case collaborationcommand.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case collaborationcommand.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case collaborationcommand.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case collaborationcommand.FieldDeviceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value != nil {
				_m.DeviceID = *value
			}
		case collaborationcommand.FieldThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thread_id", values[i])
			} else if value.Valid {
				_m.ThreadID = value.String
			}
		case collaborationcommand.FieldIdempotencyKey:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value != nil {
				_m.IdempotencyKey = *value
			}
		case collaborationcommand.FieldPromptSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_sha256", values[i])
			} else if value.Valid {
				_m.PromptSha256 = value.String
			}
		case collaborationcommand.FieldPromptBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_bytes", values[i])
			} else if value.Valid {
				_m.PromptBytes = int(value.Int64)
			}
		case collaborationcommand.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = collaborationcommand.Status(value.String)
			}
		case collaborationcommand.FieldTurnID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field turn_id", values[i])
			} else if value.Valid {
				_m.TurnID = new(string)
				*_m.TurnID = value.String
			}
		case collaborationcommand.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case collaborationcommand.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case collaborationcommand.FieldDispatchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dispatched_at", values[i])
			} else if value.Valid {
				_m.DispatchedAt = new(time.Time)
				*_m.DispatchedAt = value.Time
			}
		case collaborationcommand.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case collaborationcommand.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CollaborationCommand.
// This includes values selected through modifiers, order, etc.
func (_m *CollaborationCommand) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CollaborationCommand entity.
func (_m *CollaborationCommand) QueryUser() *UserQuery {
	return NewCollaborationCommandClient(_m.config).QueryUser(_m)
}

// QueryDevice queries the "device" edge of the CollaborationCommand entity.
func (_m *CollaborationCommand) QueryDevice() *CollaborationDeviceQuery {
	return NewCollaborationCommandClient(_m.config).QueryDevice(_m)
}

// QueryCharge queries the "charge" edge of the CollaborationCommand entity.
func (_m *CollaborationCommand) QueryCharge() *CollaborationChargeQuery {
	return NewCollaborationCommandClient(_m.config).QueryCharge(_m)
}

// Update returns a builder for updating this CollaborationCommand.
// Note that you need to call CollaborationCommand.Unwrap() before calling this method if this CollaborationCommand
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CollaborationCommand) Update() *CollaborationCommandUpdateOne {
	return NewCollaborationCommandClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CollaborationCommand entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CollaborationCommand) Unwrap() *CollaborationCommand {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CollaborationCommand is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CollaborationCommand) String() string {
	var builder strings.Builder
	builder.WriteString("CollaborationCommand(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("thread_id=")
	builder.WriteString(_m.ThreadID)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.IdempotencyKey))
	builder.WriteString(", ")
	builder.WriteString("prompt_sha256=")
	builder.WriteString(_m.PromptSha256)
	builder.WriteString(", ")
	builder.WriteString("prompt_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptBytes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.TurnID; v != nil {
		builder.WriteString("turn_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DispatchedAt; v != nil {
		builder.WriteString("dispatched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CollaborationCommands is a parsable slice of CollaborationCommand.
type CollaborationCommands []*CollaborationCommand
