// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// CollaborationCommandUpdate is the builder for updating CollaborationCommand entities.
type CollaborationCommandUpdate struct {
	config
	hooks    []Hook
	mutation *CollaborationCommandMutation
}

// Where appends a list predicates to the CollaborationCommandUpdate builder.
func (_u *CollaborationCommandUpdate) Where(ps ...predicate.CollaborationCommand) *CollaborationCommandUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollaborationCommandUpdate) SetUpdatedAt(v time.Time) *CollaborationCommandUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CollaborationCommandUpdate) SetStatus(v collaborationcommand.Status) *CollaborationCommandUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableStatus(v *collaborationcommand.Status) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTurnID sets the "turn_id" field.
func (_u *CollaborationCommandUpdate) SetTurnID(v string) *CollaborationCommandUpdate {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableTurnID(v *string) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// ClearTurnID clears the value of the "turn_id" field.
func (_u *CollaborationCommandUpdate) ClearTurnID() *CollaborationCommandUpdate {
	_u.mutation.ClearTurnID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CollaborationCommandUpdate) SetErrorCode(v string) *CollaborationCommandUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableErrorCode(v *string) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CollaborationCommandUpdate) ClearErrorCode() *CollaborationCommandUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CollaborationCommandUpdate) SetExpiresAt(v time.Time) *CollaborationCommandUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableExpiresAt(v *time.Time) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *CollaborationCommandUpdate) SetDispatchedAt(v time.Time) *CollaborationCommandUpdate {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableDispatchedAt(v *time.Time) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *CollaborationCommandUpdate) ClearDispatchedAt() *CollaborationCommandUpdate {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CollaborationCommandUpdate) SetStartedAt(v time.Time) *CollaborationCommandUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableStartedAt(v *time.Time) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CollaborationCommandUpdate) ClearStartedAt() *CollaborationCommandUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CollaborationCommandUpdate) SetCompletedAt(v time.Time) *CollaborationCommandUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableCompletedAt(v *time.Time) *CollaborationCommandUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CollaborationCommandUpdate) ClearCompletedAt() *CollaborationCommandUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetChargeID sets the "charge" edge to the CollaborationCharge entity by ID.
func (_u *CollaborationCommandUpdate) SetChargeID(id uuid.UUID) *CollaborationCommandUpdate {
	_u.mutation.SetChargeID(id)
	return _u
}

// SetNillableChargeID sets the "charge" edge to the CollaborationCharge entity by ID if the given value is not nil.
func (_u *CollaborationCommandUpdate) SetNillableChargeID(id *uuid.UUID) *CollaborationCommandUpdate {
	if id != nil {
		_u = _u.SetChargeID(*id)
	}
	return _u
}

// SetCharge sets the "charge" edge to the CollaborationCharge entity.
func (_u *CollaborationCommandUpdate) SetCharge(v *CollaborationCharge) *CollaborationCommandUpdate {
	return _u.SetChargeID(v.ID)
}

// Mutation returns the CollaborationCommandMutation object of the builder.
func (_u *CollaborationCommandUpdate) Mutation() *CollaborationCommandMutation {
	return _u.mutation
}

// ClearCharge clears the "charge" edge to the CollaborationCharge entity.
func (_u *CollaborationCommandUpdate) ClearCharge() *CollaborationCommandUpdate {
	_u.mutation.ClearCharge()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollaborationCommandUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationCommandUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollaborationCommandUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationCommandUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollaborationCommandUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collaborationcommand.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationCommandUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := collaborationcommand.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TurnID(); ok {
		if err := collaborationcommand.TurnIDValidator(v); err != nil {
			return &ValidationError{Name: "turn_id", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.turn_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := collaborationcommand.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCommand.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCommand.device"`)
	}
	return nil
}

func (_u *CollaborationCommandUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationcommand.Table, collaborationcommand.Columns, sqlgraph.NewFieldSpec(collaborationcommand.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationcommand.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(collaborationcommand.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TurnID(); ok {
		_spec.SetField(collaborationcommand.FieldTurnID, field.TypeString, value)
	}
	if _u.mutation.TurnIDCleared() {
		_spec.ClearField(collaborationcommand.FieldTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(collaborationcommand.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(collaborationcommand.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(collaborationcommand.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(collaborationcommand.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(collaborationcommand.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(collaborationcommand.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ChargeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   collaborationcommand.ChargeTable,
			Columns: []string{collaborationcommand.ChargeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChargeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   collaborationcommand.ChargeTable,
			Columns: []string{collaborationcommand.ChargeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationcommand.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollaborationCommandUpdateOne is the builder for updating a single CollaborationCommand entity.
type CollaborationCommandUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollaborationCommandMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollaborationCommandUpdateOne) SetUpdatedAt(v time.Time) *CollaborationCommandUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CollaborationCommandUpdateOne) SetStatus(v collaborationcommand.Status) *CollaborationCommandUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableStatus(v *collaborationcommand.Status) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTurnID sets the "turn_id" field.
func (_u *CollaborationCommandUpdateOne) SetTurnID(v string) *CollaborationCommandUpdateOne {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableTurnID(v *string) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// ClearTurnID clears the value of the "turn_id" field.
func (_u *CollaborationCommandUpdateOne) ClearTurnID() *CollaborationCommandUpdateOne {
	_u.mutation.ClearTurnID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CollaborationCommandUpdateOne) SetErrorCode(v string) *CollaborationCommandUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableErrorCode(v *string) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CollaborationCommandUpdateOne) ClearErrorCode() *CollaborationCommandUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CollaborationCommandUpdateOne) SetExpiresAt(v time.Time) *CollaborationCommandUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableExpiresAt(v *time.Time) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *CollaborationCommandUpdateOne) SetDispatchedAt(v time.Time) *CollaborationCommandUpdateOne {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableDispatchedAt(v *time.Time) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *CollaborationCommandUpdateOne) ClearDispatchedAt() *CollaborationCommandUpdateOne {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CollaborationCommandUpdateOne) SetStartedAt(v time.Time) *CollaborationCommandUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableStartedAt(v *time.Time) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CollaborationCommandUpdateOne) ClearStartedAt() *CollaborationCommandUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CollaborationCommandUpdateOne) SetCompletedAt(v time.Time) *CollaborationCommandUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableCompletedAt(v *time.Time) *CollaborationCommandUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CollaborationCommandUpdateOne) ClearCompletedAt() *CollaborationCommandUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetChargeID sets the "charge" edge to the CollaborationCharge entity by ID.
func (_u *CollaborationCommandUpdateOne) SetChargeID(id uuid.UUID) *CollaborationCommandUpdateOne {
	_u.mutation.SetChargeID(id)
	return _u
}

// SetNillableChargeID sets the "charge" edge to the CollaborationCharge entity by ID if the given value is not nil.
func (_u *CollaborationCommandUpdateOne) SetNillableChargeID(id *uuid.UUID) *CollaborationCommandUpdateOne {
	if id != nil {
		_u = _u.SetChargeID(*id)
	}
	return _u
}

// SetCharge sets the "charge" edge to the CollaborationCharge entity.
func (_u *CollaborationCommandUpdateOne) SetCharge(v *CollaborationCharge) *CollaborationCommandUpdateOne {
	return _u.SetChargeID(v.ID)
}

// Mutation returns the CollaborationCommandMutation object of the builder.
func (_u *CollaborationCommandUpdateOne) Mutation() *CollaborationCommandMutation {
	return _u.mutation
}

// ClearCharge clears the "charge" edge to the CollaborationCharge entity.
func (_u *CollaborationCommandUpdateOne) ClearCharge() *CollaborationCommandUpdateOne {
	_u.mutation.ClearCharge()
	return _u
}

// Where appends a list predicates to the CollaborationCommandUpdate builder.
func (_u *CollaborationCommandUpdateOne) Where(ps ...predicate.CollaborationCommand) *CollaborationCommandUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollaborationCommandUpdateOne) Select(field string, fields ...string) *CollaborationCommandUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CollaborationCommand entity.
func (_u *CollaborationCommandUpdateOne) Save(ctx context.Context) (*CollaborationCommand, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationCommandUpdateOne) SaveX(ctx context.Context) *CollaborationCommand {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollaborationCommandUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationCommandUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollaborationCommandUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collaborationcommand.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationCommandUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := collaborationcommand.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TurnID(); ok {
		if err := collaborationcommand.TurnIDValidator(v); err != nil {
			return &ValidationError{Name: "turn_id", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.turn_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := collaborationcommand.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CollaborationCommand.error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCommand.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCommand.device"`)
	}
	return nil
}

func (_u *CollaborationCommandUpdateOne) sqlSave(ctx context.Context) (_node *CollaborationCommand, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationcommand.Table, collaborationcommand.Columns, sqlgraph.NewFieldSpec(collaborationcommand.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollaborationCommand.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collaborationcommand.FieldID)
		for _, f := range fields {
			if !collaborationcommand.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collaborationcommand.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationcommand.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(collaborationcommand.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TurnID(); ok {
		_spec.SetField(collaborationcommand.FieldTurnID, field.TypeString, value)
	}
	if _u.mutation.TurnIDCleared() {
		_spec.ClearField(collaborationcommand.FieldTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(collaborationcommand.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(collaborationcommand.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(collaborationcommand.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(collaborationcommand.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(collaborationcommand.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(collaborationcommand.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(collaborationcommand.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ChargeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   collaborationcommand.ChargeTable,
			Columns: []string{collaborationcommand.ChargeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChargeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   collaborationcommand.ChargeTable,
			Columns: []string{collaborationcommand.ChargeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CollaborationCommand{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationcommand.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
