// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationChargeCreate is the builder for creating a CollaborationCharge entity.
type CollaborationChargeCreate struct {
	config
	mutation *CollaborationChargeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCommandID sets the "command_id" field.
func (_c *CollaborationChargeCreate) SetCommandID(v uuid.UUID) *CollaborationChargeCreate {
	_c.mutation.SetCommandID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CollaborationChargeCreate) SetUserID(v int64) *CollaborationChargeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CollaborationChargeCreate) SetAmount(v string) *CollaborationChargeCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CollaborationChargeCreate) SetCurrency(v string) *CollaborationChargeCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *CollaborationChargeCreate) SetNillableCurrency(v *string) *CollaborationChargeCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CollaborationChargeCreate) SetStatus(v collaborationcharge.Status) *CollaborationChargeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CollaborationChargeCreate) SetNillableStatus(v *collaborationcharge.Status) *CollaborationChargeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *CollaborationChargeCreate) SetBalanceBefore(v string) *CollaborationChargeCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *CollaborationChargeCreate) SetBalanceAfter(v string) *CollaborationChargeCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *CollaborationChargeCreate) SetReason(v string) *CollaborationChargeCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *CollaborationChargeCreate) SetNillableReason(v *string) *CollaborationChargeCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetChargedAt sets the "charged_at" field.
func (_c *CollaborationChargeCreate) SetChargedAt(v time.Time) *CollaborationChargeCreate {
	_c.mutation.SetChargedAt(v)
	return _c
}

// SetNillableChargedAt sets the "charged_at" field if the given value is not nil.
func (_c *CollaborationChargeCreate) SetNillableChargedAt(v *time.Time) *CollaborationChargeCreate {
	if v != nil {
		_c.SetChargedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CollaborationChargeCreate) SetID(v uuid.UUID) *CollaborationChargeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CollaborationChargeCreate) SetNillableID(v *uuid.UUID) *CollaborationChargeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCommand sets the "command" edge to the CollaborationCommand entity.
func (_c *CollaborationChargeCreate) SetCommand(v *CollaborationCommand) *CollaborationChargeCreate {
	return _c.SetCommandID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *CollaborationChargeCreate) SetUser(v *User) *CollaborationChargeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CollaborationChargeMutation object of the builder.
func (_c *CollaborationChargeCreate) Mutation() *CollaborationChargeMutation {
	return _c.mutation
}

// Save creates the CollaborationCharge in the database.
func (_c *CollaborationChargeCreate) Save(ctx context.Context) (*CollaborationCharge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CollaborationChargeCreate) SaveX(ctx context.Context) *CollaborationCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationChargeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationChargeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CollaborationChargeCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := collaborationcharge.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := collaborationcharge.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ChargedAt(); !ok {
		v := collaborationcharge.DefaultChargedAt()
		_c.mutation.SetChargedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := collaborationcharge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CollaborationChargeCreate) check() error {
	if _, ok := _c.mutation.CommandID(); !ok {
		return &ValidationError{Name: "command_id", err: errors.New(`ent: missing required field "CollaborationCharge.command_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CollaborationCharge.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CollaborationCharge.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CollaborationCharge.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := collaborationcharge.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CollaborationCharge.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CollaborationCharge.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := collaborationcharge.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationCharge.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "CollaborationCharge.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "CollaborationCharge.balance_after"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := collaborationcharge.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "CollaborationCharge.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChargedAt(); !ok {
		return &ValidationError{Name: "charged_at", err: errors.New(`ent: missing required field "CollaborationCharge.charged_at"`)}
	}
	if len(_c.mutation.CommandIDs()) == 0 {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required edge "CollaborationCharge.command"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CollaborationCharge.user"`)}
	}
	return nil
}

func (_c *CollaborationChargeCreate) sqlSave(ctx context.Context) (*CollaborationCharge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CollaborationChargeCreate) createSpec() (*CollaborationCharge, *sqlgraph.CreateSpec) {
	var (
		_node = &CollaborationCharge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(collaborationcharge.Table, sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(collaborationcharge.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(collaborationcharge.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(collaborationcharge.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(collaborationcharge.FieldBalanceBefore, field.TypeString, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(collaborationcharge.FieldBalanceAfter, field.TypeString, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(collaborationcharge.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.ChargedAt(); ok {
		_spec.SetField(collaborationcharge.FieldChargedAt, field.TypeTime, value)
		_node.ChargedAt = value
	}
	if nodes := _c.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   collaborationcharge.CommandTable,
			Columns: []string{collaborationcharge.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcommand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CommandID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collaborationcharge.UserTable,
			Columns: []string{collaborationcharge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationCharge.Create().
//		SetCommandID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationChargeUpsert) {
//			SetCommandID(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationChargeCreate) OnConflict(opts ...sql.ConflictOption) *CollaborationChargeUpsertOne {
	_c.conflict = opts
	return &CollaborationChargeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationChargeCreate) OnConflictColumns(columns ...string) *CollaborationChargeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationChargeUpsertOne{
		create: _c,
	}
}

type (
	// CollaborationChargeUpsertOne is the builder for "upsert"-ing
	//  one CollaborationCharge node.
	CollaborationChargeUpsertOne struct {
		create *CollaborationChargeCreate
	}

	// CollaborationChargeUpsert is the "OnConflict" setter.
	CollaborationChargeUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationcharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationChargeUpsertOne) UpdateNewValues() *CollaborationChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(collaborationcharge.FieldID)
		}
		if _, exists := u.create.mutation.CommandID(); exists {
			s.SetIgnore(collaborationcharge.FieldCommandID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(collaborationcharge.FieldUserID)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(collaborationcharge.FieldAmount)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(collaborationcharge.FieldCurrency)
		}
		if _, exists := u.create.mutation.Status(); exists {
			s.SetIgnore(collaborationcharge.FieldStatus)
		}
		if _, exists := u.create.mutation.BalanceBefore(); exists {
			s.SetIgnore(collaborationcharge.FieldBalanceBefore)
		}
		if _, exists := u.create.mutation.BalanceAfter(); exists {
			s.SetIgnore(collaborationcharge.FieldBalanceAfter)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(collaborationcharge.FieldReason)
		}
		if _, exists := u.create.mutation.ChargedAt(); exists {
			s.SetIgnore(collaborationcharge.FieldChargedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CollaborationChargeUpsertOne) Ignore() *CollaborationChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationChargeUpsertOne) DoNothing() *CollaborationChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationChargeCreate.OnConflict
// documentation for more info.
func (u *CollaborationChargeUpsertOne) Update(set func(*CollaborationChargeUpsert)) *CollaborationChargeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationChargeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *CollaborationChargeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationChargeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationChargeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CollaborationChargeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CollaborationChargeUpsertOne.ID is not supported by MySQL driver. Use CollaborationChargeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CollaborationChargeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CollaborationChargeCreateBulk is the builder for creating many CollaborationCharge entities in bulk.
type CollaborationChargeCreateBulk struct {
	config
	err      error
	builders []*CollaborationChargeCreate
	conflict []sql.ConflictOption
}

// Save creates the CollaborationCharge entities in the database.
func (_c *CollaborationChargeCreateBulk) Save(ctx context.Context) ([]*CollaborationCharge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CollaborationCharge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CollaborationChargeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CollaborationChargeCreateBulk) SaveX(ctx context.Context) []*CollaborationCharge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationChargeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationChargeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationCharge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationChargeUpsert) {
//			SetCommandID(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationChargeCreateBulk) OnConflict(opts ...sql.ConflictOption) *CollaborationChargeUpsertBulk {
	_c.conflict = opts
	return &CollaborationChargeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationChargeCreateBulk) OnConflictColumns(columns ...string) *CollaborationChargeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationChargeUpsertBulk{
		create: _c,
	}
}

// CollaborationChargeUpsertBulk is the builder for "upsert"-ing
// a bulk of CollaborationCharge nodes.
type CollaborationChargeUpsertBulk struct {
	create *CollaborationChargeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationcharge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationChargeUpsertBulk) UpdateNewValues() *CollaborationChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(collaborationcharge.FieldID)
			}
			if _, exists := b.mutation.CommandID(); exists {
				s.SetIgnore(collaborationcharge.FieldCommandID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(collaborationcharge.FieldUserID)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(collaborationcharge.FieldAmount)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(collaborationcharge.FieldCurrency)
			}
			if _, exists := b.mutation.Status(); exists {
				s.SetIgnore(collaborationcharge.FieldStatus)
			}
			if _, exists := b.mutation.BalanceBefore(); exists {
				s.SetIgnore(collaborationcharge.FieldBalanceBefore)
			}
			if _, exists := b.mutation.BalanceAfter(); exists {
				s.SetIgnore(collaborationcharge.FieldBalanceAfter)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(collaborationcharge.FieldReason)
			}
			if _, exists := b.mutation.ChargedAt(); exists {
				s.SetIgnore(collaborationcharge.FieldChargedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationCharge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CollaborationChargeUpsertBulk) Ignore() *CollaborationChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationChargeUpsertBulk) DoNothing() *CollaborationChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationChargeCreateBulk.OnConflict
// documentation for more info.
func (u *CollaborationChargeUpsertBulk) Update(set func(*CollaborationChargeUpsert)) *CollaborationChargeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationChargeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *CollaborationChargeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CollaborationChargeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationChargeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationChargeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
