// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/collaborationdevice"
	"github.com/Wei-Shaw/sub2api/ent/collaborationsyncrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/google/uuid"
)

// CollaborationDeviceCreate is the builder for creating a CollaborationDevice entity.
type CollaborationDeviceCreate struct {
	config
	mutation *CollaborationDeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CollaborationDeviceCreate) SetCreatedAt(v time.Time) *CollaborationDeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableCreatedAt(v *time.Time) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CollaborationDeviceCreate) SetUpdatedAt(v time.Time) *CollaborationDeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableUpdatedAt(v *time.Time) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CollaborationDeviceCreate) SetUserID(v int64) *CollaborationDeviceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_c *CollaborationDeviceCreate) SetInstallationIDHash(v string) *CollaborationDeviceCreate {
	_c.mutation.SetInstallationIDHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CollaborationDeviceCreate) SetName(v string) *CollaborationDeviceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *CollaborationDeviceCreate) SetPlatform(v collaborationdevice.Platform) *CollaborationDeviceCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetPlatformVersion sets the "platform_version" field.
func (_c *CollaborationDeviceCreate) SetPlatformVersion(v string) *CollaborationDeviceCreate {
	_c.mutation.SetPlatformVersion(v)
	return _c
}

// SetNillablePlatformVersion sets the "platform_version" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillablePlatformVersion(v *string) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetPlatformVersion(*v)
	}
	return _c
}

// SetCompanionVersion sets the "companion_version" field.
func (_c *CollaborationDeviceCreate) SetCompanionVersion(v string) *CollaborationDeviceCreate {
	_c.mutation.SetCompanionVersion(v)
	return _c
}

// SetCodexVersion sets the "codex_version" field.
func (_c *CollaborationDeviceCreate) SetCodexVersion(v string) *CollaborationDeviceCreate {
	_c.mutation.SetCodexVersion(v)
	return _c
}

// SetNillableCodexVersion sets the "codex_version" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableCodexVersion(v *string) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetCodexVersion(*v)
	}
	return _c
}

// SetProtocolVersion sets the "protocol_version" field.
func (_c *CollaborationDeviceCreate) SetProtocolVersion(v int) *CollaborationDeviceCreate {
	_c.mutation.SetProtocolVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CollaborationDeviceCreate) SetStatus(v collaborationdevice.Status) *CollaborationDeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableStatus(v *collaborationdevice.Status) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *CollaborationDeviceCreate) SetCapabilities(v map[string]interface{}) *CollaborationDeviceCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *CollaborationDeviceCreate) SetLastSeenAt(v time.Time) *CollaborationDeviceCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableLastSeenAt(v *time.Time) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *CollaborationDeviceCreate) SetRevokedAt(v time.Time) *CollaborationDeviceCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableRevokedAt(v *time.Time) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRegisteredAt sets the "registered_at" field.
func (_c *CollaborationDeviceCreate) SetRegisteredAt(v time.Time) *CollaborationDeviceCreate {
	_c.mutation.SetRegisteredAt(v)
	return _c
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableRegisteredAt(v *time.Time) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetRegisteredAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CollaborationDeviceCreate) SetID(v uuid.UUID) *CollaborationDeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CollaborationDeviceCreate) SetNillableID(v *uuid.UUID) *CollaborationDeviceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CollaborationDeviceCreate) SetUser(v *User) *CollaborationDeviceCreate {
	return _c.SetUserID(v.ID)
}

// AddSyncRequestIDs adds the "sync_requests" edge to the CollaborationSyncRequest entity by IDs.
func (_c *CollaborationDeviceCreate) AddSyncRequestIDs(ids ...uuid.UUID) *CollaborationDeviceCreate {
	_c.mutation.AddSyncRequestIDs(ids...)
	return _c
}

// AddSyncRequests adds the "sync_requests" edges to the CollaborationSyncRequest entity.
func (_c *CollaborationDeviceCreate) AddSyncRequests(v ...*CollaborationSyncRequest) *CollaborationDeviceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyncRequestIDs(ids...)
}

// AddCommandIDs adds the "commands" edge to the CollaborationCommand entity by IDs.
func (_c *CollaborationDeviceCreate) AddCommandIDs(ids ...uuid.UUID) *CollaborationDeviceCreate {
	_c.mutation.AddCommandIDs(ids...)
	return _c
}

// AddCommands adds the "commands" edges to the CollaborationCommand entity.
func (_c *CollaborationDeviceCreate) AddCommands(v ...*CollaborationCommand) *CollaborationDeviceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommandIDs(ids...)
}

// Mutation returns the CollaborationDeviceMutation object of the builder.
func (_c *CollaborationDeviceCreate) Mutation() *CollaborationDeviceMutation {
	return _c.mutation
}

// Save creates the CollaborationDevice in the database.
func (_c *CollaborationDeviceCreate) Save(ctx context.Context) (*CollaborationDevice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CollaborationDeviceCreate) SaveX(ctx context.Context) *CollaborationDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationDeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationDeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CollaborationDeviceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := collaborationdevice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := collaborationdevice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := collaborationdevice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		v := collaborationdevice.DefaultCapabilities()
		_c.mutation.SetCapabilities(v)
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		v := collaborationdevice.DefaultRegisteredAt()
		_c.mutation.SetRegisteredAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := collaborationdevice.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CollaborationDeviceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CollaborationDevice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CollaborationDevice.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CollaborationDevice.user_id"`)}
	}
	if _, ok := _c.mutation.InstallationIDHash(); !ok {
		return &ValidationError{Name: "installation_id_hash", err: errors.New(`ent: missing required field "CollaborationDevice.installation_id_hash"`)}
	}
	if v, ok := _c.mutation.InstallationIDHash(); ok {
		if err := collaborationdevice.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.installation_id_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CollaborationDevice.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := collaborationdevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "CollaborationDevice.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := collaborationdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.platform": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PlatformVersion(); ok {
		if err := collaborationdevice.PlatformVersionValidator(v); err != nil {
			return &ValidationError{Name: "platform_version", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.platform_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompanionVersion(); !ok {
		return &ValidationError{Name: "companion_version", err: errors.New(`ent: missing required field "CollaborationDevice.companion_version"`)}
	}
	if v, ok := _c.mutation.CompanionVersion(); ok {
		if err := collaborationdevice.CompanionVersionValidator(v); err != nil {
			return &ValidationError{Name: "companion_version", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.companion_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CodexVersion(); ok {
		if err := collaborationdevice.CodexVersionValidator(v); err != nil {
			return &ValidationError{Name: "codex_version", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.codex_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProtocolVersion(); !ok {
		return &ValidationError{Name: "protocol_version", err: errors.New(`ent: missing required field "CollaborationDevice.protocol_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CollaborationDevice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := collaborationdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationDevice.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "CollaborationDevice.capabilities"`)}
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		return &ValidationError{Name: "registered_at", err: errors.New(`ent: missing required field "CollaborationDevice.registered_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CollaborationDevice.user"`)}
	}
	return nil
}

func (_c *CollaborationDeviceCreate) sqlSave(ctx context.Context) (*CollaborationDevice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CollaborationDeviceCreate) createSpec() (*CollaborationDevice, *sqlgraph.CreateSpec) {
	var (
		_node = &CollaborationDevice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(collaborationdevice.Table, sqlgraph.NewFieldSpec(collaborationdevice.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(collaborationdevice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationdevice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.InstallationIDHash(); ok {
		_spec.SetField(collaborationdevice.FieldInstallationIDHash, field.TypeString, value)
		_node.InstallationIDHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(collaborationdevice.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(collaborationdevice.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.PlatformVersion(); ok {
		_spec.SetField(collaborationdevice.FieldPlatformVersion, field.TypeString, value)
		_node.PlatformVersion = &value
	}
	if value, ok := _c.mutation.CompanionVersion(); ok {
		_spec.SetField(collaborationdevice.FieldCompanionVersion, field.TypeString, value)
		_node.CompanionVersion = value
	}
	if value, ok := _c.mutation.CodexVersion(); ok {
		_spec.SetField(collaborationdevice.FieldCodexVersion, field.TypeString, value)
		_node.CodexVersion = &value
	}
	if value, ok := _c.mutation.ProtocolVersion(); ok {
		_spec.SetField(collaborationdevice.FieldProtocolVersion, field.TypeInt, value)
		_node.ProtocolVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(collaborationdevice.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(collaborationdevice.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(collaborationdevice.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(collaborationdevice.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RegisteredAt(); ok {
		_spec.SetField(collaborationdevice.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collaborationdevice.UserTable,
			Columns: []string{collaborationdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SyncRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collaborationdevice.SyncRequestsTable,
			Columns: []string{collaborationdevice.SyncRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationsyncrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommandsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collaborationdevice.CommandsTable,
			Columns: []string{collaborationdevice.CommandsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collaborationcommand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationDevice.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationDeviceCreate) OnConflict(opts ...sql.ConflictOption) *CollaborationDeviceUpsertOne {
	_c.conflict = opts
	return &CollaborationDeviceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationDeviceCreate) OnConflictColumns(columns ...string) *CollaborationDeviceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationDeviceUpsertOne{
		create: _c,
	}
}

type (
	// CollaborationDeviceUpsertOne is the builder for "upsert"-ing
	//  one CollaborationDevice node.
	CollaborationDeviceUpsertOne struct {
		create *CollaborationDeviceCreate
	}

	// CollaborationDeviceUpsert is the "OnConflict" setter.
	CollaborationDeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationDeviceUpsert) SetUpdatedAt(v time.Time) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateUpdatedAt() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldUpdatedAt)
	return u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *CollaborationDeviceUpsert) SetInstallationIDHash(v string) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldInstallationIDHash, v)
	return u
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateInstallationIDHash() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldInstallationIDHash)
	return u
}

// SetName sets the "name" field.
func (u *CollaborationDeviceUpsert) SetName(v string) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateName() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *CollaborationDeviceUpsert) SetPlatform(v collaborationdevice.Platform) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdatePlatform() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldPlatform)
	return u
}

// SetPlatformVersion sets the "platform_version" field.
func (u *CollaborationDeviceUpsert) SetPlatformVersion(v string) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldPlatformVersion, v)
	return u
}

// UpdatePlatformVersion sets the "platform_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdatePlatformVersion() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldPlatformVersion)
	return u
}

// ClearPlatformVersion clears the value of the "platform_version" field.
func (u *CollaborationDeviceUpsert) ClearPlatformVersion() *CollaborationDeviceUpsert {
	u.SetNull(collaborationdevice.FieldPlatformVersion)
	return u
}

// SetCompanionVersion sets the "companion_version" field.
func (u *CollaborationDeviceUpsert) SetCompanionVersion(v string) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldCompanionVersion, v)
	return u
}

// UpdateCompanionVersion sets the "companion_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateCompanionVersion() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldCompanionVersion)
	return u
}

// SetCodexVersion sets the "codex_version" field.
func (u *CollaborationDeviceUpsert) SetCodexVersion(v string) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldCodexVersion, v)
	return u
}

// UpdateCodexVersion sets the "codex_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateCodexVersion() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldCodexVersion)
	return u
}

// ClearCodexVersion clears the value of the "codex_version" field.
func (u *CollaborationDeviceUpsert) ClearCodexVersion() *CollaborationDeviceUpsert {
	u.SetNull(collaborationdevice.FieldCodexVersion)
	return u
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *CollaborationDeviceUpsert) SetProtocolVersion(v int) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldProtocolVersion, v)
	return u
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateProtocolVersion() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldProtocolVersion)
	return u
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *CollaborationDeviceUpsert) AddProtocolVersion(v int) *CollaborationDeviceUpsert {
	u.Add(collaborationdevice.FieldProtocolVersion, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CollaborationDeviceUpsert) SetStatus(v collaborationdevice.Status) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateStatus() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldStatus)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *CollaborationDeviceUpsert) SetCapabilities(v map[string]interface{}) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateCapabilities() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldCapabilities)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CollaborationDeviceUpsert) SetLastSeenAt(v time.Time) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateLastSeenAt() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CollaborationDeviceUpsert) ClearLastSeenAt() *CollaborationDeviceUpsert {
	u.SetNull(collaborationdevice.FieldLastSeenAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CollaborationDeviceUpsert) SetRevokedAt(v time.Time) *CollaborationDeviceUpsert {
	u.Set(collaborationdevice.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsert) UpdateRevokedAt() *CollaborationDeviceUpsert {
	u.SetExcluded(collaborationdevice.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CollaborationDeviceUpsert) ClearRevokedAt() *CollaborationDeviceUpsert {
	u.SetNull(collaborationdevice.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationdevice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationDeviceUpsertOne) UpdateNewValues() *CollaborationDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(collaborationdevice.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(collaborationdevice.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(collaborationdevice.FieldUserID)
		}
		if _, exists := u.create.mutation.RegisteredAt(); exists {
			s.SetIgnore(collaborationdevice.FieldRegisteredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CollaborationDeviceUpsertOne) Ignore() *CollaborationDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationDeviceUpsertOne) DoNothing() *CollaborationDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationDeviceCreate.OnConflict
// documentation for more info.
func (u *CollaborationDeviceUpsertOne) Update(set func(*CollaborationDeviceUpsert)) *CollaborationDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationDeviceUpsertOne) SetUpdatedAt(v time.Time) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateUpdatedAt() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *CollaborationDeviceUpsertOne) SetInstallationIDHash(v string) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetInstallationIDHash(v)
	})
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateInstallationIDHash() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateInstallationIDHash()
	})
}

// SetName sets the "name" field.
func (u *CollaborationDeviceUpsertOne) SetName(v string) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateName() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *CollaborationDeviceUpsertOne) SetPlatform(v collaborationdevice.Platform) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdatePlatform() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformVersion sets the "platform_version" field.
func (u *CollaborationDeviceUpsertOne) SetPlatformVersion(v string) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetPlatformVersion(v)
	})
}

// UpdatePlatformVersion sets the "platform_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdatePlatformVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdatePlatformVersion()
	})
}

// ClearPlatformVersion clears the value of the "platform_version" field.
func (u *CollaborationDeviceUpsertOne) ClearPlatformVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearPlatformVersion()
	})
}

// SetCompanionVersion sets the "companion_version" field.
func (u *CollaborationDeviceUpsertOne) SetCompanionVersion(v string) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCompanionVersion(v)
	})
}

// UpdateCompanionVersion sets the "companion_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateCompanionVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCompanionVersion()
	})
}

// SetCodexVersion sets the "codex_version" field.
func (u *CollaborationDeviceUpsertOne) SetCodexVersion(v string) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCodexVersion(v)
	})
}

// UpdateCodexVersion sets the "codex_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateCodexVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCodexVersion()
	})
}

// ClearCodexVersion clears the value of the "codex_version" field.
func (u *CollaborationDeviceUpsertOne) ClearCodexVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearCodexVersion()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *CollaborationDeviceUpsertOne) SetProtocolVersion(v int) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetProtocolVersion(v)
	})
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *CollaborationDeviceUpsertOne) AddProtocolVersion(v int) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.AddProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateProtocolVersion() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateProtocolVersion()
	})
}

// SetStatus sets the "status" field.
func (u *CollaborationDeviceUpsertOne) SetStatus(v collaborationdevice.Status) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateStatus() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateStatus()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *CollaborationDeviceUpsertOne) SetCapabilities(v map[string]interface{}) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateCapabilities() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCapabilities()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CollaborationDeviceUpsertOne) SetLastSeenAt(v time.Time) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateLastSeenAt() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CollaborationDeviceUpsertOne) ClearLastSeenAt() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CollaborationDeviceUpsertOne) SetRevokedAt(v time.Time) *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertOne) UpdateRevokedAt() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CollaborationDeviceUpsertOne) ClearRevokedAt() *CollaborationDeviceUpsertOne {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CollaborationDeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationDeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationDeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CollaborationDeviceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CollaborationDeviceUpsertOne.ID is not supported by MySQL driver. Use CollaborationDeviceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CollaborationDeviceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CollaborationDeviceCreateBulk is the builder for creating many CollaborationDevice entities in bulk.
type CollaborationDeviceCreateBulk struct {
	config
	err      error
	builders []*CollaborationDeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the CollaborationDevice entities in the database.
func (_c *CollaborationDeviceCreateBulk) Save(ctx context.Context) ([]*CollaborationDevice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CollaborationDevice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CollaborationDeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CollaborationDeviceCreateBulk) SaveX(ctx context.Context) []*CollaborationDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollaborationDeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollaborationDeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CollaborationDevice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CollaborationDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CollaborationDeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *CollaborationDeviceUpsertBulk {
	_c.conflict = opts
	return &CollaborationDeviceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CollaborationDeviceCreateBulk) OnConflictColumns(columns ...string) *CollaborationDeviceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CollaborationDeviceUpsertBulk{
		create: _c,
	}
}

// CollaborationDeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of CollaborationDevice nodes.
type CollaborationDeviceUpsertBulk struct {
	create *CollaborationDeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(collaborationdevice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CollaborationDeviceUpsertBulk) UpdateNewValues() *CollaborationDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(collaborationdevice.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(collaborationdevice.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(collaborationdevice.FieldUserID)
			}
			if _, exists := b.mutation.RegisteredAt(); exists {
				s.SetIgnore(collaborationdevice.FieldRegisteredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CollaborationDevice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CollaborationDeviceUpsertBulk) Ignore() *CollaborationDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CollaborationDeviceUpsertBulk) DoNothing() *CollaborationDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CollaborationDeviceCreateBulk.OnConflict
// documentation for more info.
func (u *CollaborationDeviceUpsertBulk) Update(set func(*CollaborationDeviceUpsert)) *CollaborationDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CollaborationDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CollaborationDeviceUpsertBulk) SetUpdatedAt(v time.Time) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateUpdatedAt() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (u *CollaborationDeviceUpsertBulk) SetInstallationIDHash(v string) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetInstallationIDHash(v)
	})
}

// UpdateInstallationIDHash sets the "installation_id_hash" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateInstallationIDHash() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateInstallationIDHash()
	})
}

// SetName sets the "name" field.
func (u *CollaborationDeviceUpsertBulk) SetName(v string) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateName() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *CollaborationDeviceUpsertBulk) SetPlatform(v collaborationdevice.Platform) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdatePlatform() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformVersion sets the "platform_version" field.
func (u *CollaborationDeviceUpsertBulk) SetPlatformVersion(v string) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetPlatformVersion(v)
	})
}

// UpdatePlatformVersion sets the "platform_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdatePlatformVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdatePlatformVersion()
	})
}

// ClearPlatformVersion clears the value of the "platform_version" field.
func (u *CollaborationDeviceUpsertBulk) ClearPlatformVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearPlatformVersion()
	})
}

// SetCompanionVersion sets the "companion_version" field.
func (u *CollaborationDeviceUpsertBulk) SetCompanionVersion(v string) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCompanionVersion(v)
	})
}

// UpdateCompanionVersion sets the "companion_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateCompanionVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCompanionVersion()
	})
}

// SetCodexVersion sets the "codex_version" field.
func (u *CollaborationDeviceUpsertBulk) SetCodexVersion(v string) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCodexVersion(v)
	})
}

// UpdateCodexVersion sets the "codex_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateCodexVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCodexVersion()
	})
}

// ClearCodexVersion clears the value of the "codex_version" field.
func (u *CollaborationDeviceUpsertBulk) ClearCodexVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearCodexVersion()
	})
}

// SetProtocolVersion sets the "protocol_version" field.
func (u *CollaborationDeviceUpsertBulk) SetProtocolVersion(v int) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetProtocolVersion(v)
	})
}

// AddProtocolVersion adds v to the "protocol_version" field.
func (u *CollaborationDeviceUpsertBulk) AddProtocolVersion(v int) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.AddProtocolVersion(v)
	})
}

// UpdateProtocolVersion sets the "protocol_version" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateProtocolVersion() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateProtocolVersion()
	})
}

// SetStatus sets the "status" field.
func (u *CollaborationDeviceUpsertBulk) SetStatus(v collaborationdevice.Status) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateStatus() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateStatus()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *CollaborationDeviceUpsertBulk) SetCapabilities(v map[string]interface{}) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateCapabilities() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateCapabilities()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *CollaborationDeviceUpsertBulk) SetLastSeenAt(v time.Time) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateLastSeenAt() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *CollaborationDeviceUpsertBulk) ClearLastSeenAt() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CollaborationDeviceUpsertBulk) SetRevokedAt(v time.Time) *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CollaborationDeviceUpsertBulk) UpdateRevokedAt() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CollaborationDeviceUpsertBulk) ClearRevokedAt() *CollaborationDeviceUpsertBulk {
	return u.Update(func(s *CollaborationDeviceUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *CollaborationDeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CollaborationDeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CollaborationDeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CollaborationDeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
