// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcommand"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CollaborationCommandDelete is the builder for deleting a CollaborationCommand entity.
type CollaborationCommandDelete struct {
	config
	hooks    []Hook
	mutation *CollaborationCommandMutation
}

// Where appends a list predicates to the CollaborationCommandDelete builder.
func (_d *CollaborationCommandDelete) Where(ps ...predicate.CollaborationCommand) *CollaborationCommandDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CollaborationCommandDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationCommandDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CollaborationCommandDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(collaborationcommand.Table, sqlgraph.NewFieldSpec(collaborationcommand.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CollaborationCommandDeleteOne is the builder for deleting a single CollaborationCommand entity.
type CollaborationCommandDeleteOne struct {
	_d *CollaborationCommandDelete
}

// Where appends a list predicates to the CollaborationCommandDelete builder.
func (_d *CollaborationCommandDeleteOne) Where(ps ...predicate.CollaborationCommand) *CollaborationCommandDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CollaborationCommandDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{collaborationcommand.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollaborationCommandDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
