// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationsyncrequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CollaborationSyncRequestUpdate is the builder for updating CollaborationSyncRequest entities.
type CollaborationSyncRequestUpdate struct {
	config
	hooks    []Hook
	mutation *CollaborationSyncRequestMutation
}

// Where appends a list predicates to the CollaborationSyncRequestUpdate builder.
func (_u *CollaborationSyncRequestUpdate) Where(ps ...predicate.CollaborationSyncRequest) *CollaborationSyncRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollaborationSyncRequestUpdate) SetUpdatedAt(v time.Time) *CollaborationSyncRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CollaborationSyncRequestUpdate) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableStatus(v *collaborationsyncrequest.Status) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CollaborationSyncRequestUpdate) SetErrorCode(v string) *CollaborationSyncRequestUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableErrorCode(v *string) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CollaborationSyncRequestUpdate) ClearErrorCode() *CollaborationSyncRequestUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdate) SetSnapshotVersion(v int64) *CollaborationSyncRequestUpdate {
	_u.mutation.ResetSnapshotVersion()
	_u.mutation.SetSnapshotVersion(v)
	return _u
}

// SetNillableSnapshotVersion sets the "snapshot_version" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableSnapshotVersion(v *int64) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetSnapshotVersion(*v)
	}
	return _u
}

// AddSnapshotVersion adds value to the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdate) AddSnapshotVersion(v int64) *CollaborationSyncRequestUpdate {
	_u.mutation.AddSnapshotVersion(v)
	return _u
}

// ClearSnapshotVersion clears the value of the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdate) ClearSnapshotVersion() *CollaborationSyncRequestUpdate {
	_u.mutation.ClearSnapshotVersion()
	return _u
}

// SetResultCount sets the "result_count" field.
func (_u *CollaborationSyncRequestUpdate) SetResultCount(v int) *CollaborationSyncRequestUpdate {
	_u.mutation.ResetResultCount()
	_u.mutation.SetResultCount(v)
	return _u
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableResultCount(v *int) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetResultCount(*v)
	}
	return _u
}

// AddResultCount adds value to the "result_count" field.
func (_u *CollaborationSyncRequestUpdate) AddResultCount(v int) *CollaborationSyncRequestUpdate {
	_u.mutation.AddResultCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CollaborationSyncRequestUpdate) SetExpiresAt(v time.Time) *CollaborationSyncRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableExpiresAt(v *time.Time) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CollaborationSyncRequestUpdate) SetCompletedAt(v time.Time) *CollaborationSyncRequestUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdate) SetNillableCompletedAt(v *time.Time) *CollaborationSyncRequestUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CollaborationSyncRequestUpdate) ClearCompletedAt() *CollaborationSyncRequestUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the CollaborationSyncRequestMutation object of the builder.
func (_u *CollaborationSyncRequestUpdate) Mutation() *CollaborationSyncRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollaborationSyncRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationSyncRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollaborationSyncRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationSyncRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollaborationSyncRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collaborationsyncrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationSyncRequestUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := collaborationsyncrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := collaborationsyncrequest.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationSyncRequest.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationSyncRequest.device"`)
	}
	return nil
}

func (_u *CollaborationSyncRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationsyncrequest.Table, collaborationsyncrequest.Columns, sqlgraph.NewFieldSpec(collaborationsyncrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldThreadID, field.TypeString)
	}
	if _u.mutation.CursorCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldCursor, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(collaborationsyncrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(collaborationsyncrequest.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.SnapshotVersion(); ok {
		_spec.SetField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotVersion(); ok {
		_spec.AddField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if _u.mutation.SnapshotVersionCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResultCount(); ok {
		_spec.SetField(collaborationsyncrequest.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultCount(); ok {
		_spec.AddField(collaborationsyncrequest.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationsyncrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollaborationSyncRequestUpdateOne is the builder for updating a single CollaborationSyncRequest entity.
type CollaborationSyncRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollaborationSyncRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollaborationSyncRequestUpdateOne) SetUpdatedAt(v time.Time) *CollaborationSyncRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CollaborationSyncRequestUpdateOne) SetStatus(v collaborationsyncrequest.Status) *CollaborationSyncRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableStatus(v *collaborationsyncrequest.Status) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CollaborationSyncRequestUpdateOne) SetErrorCode(v string) *CollaborationSyncRequestUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableErrorCode(v *string) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CollaborationSyncRequestUpdateOne) ClearErrorCode() *CollaborationSyncRequestUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdateOne) SetSnapshotVersion(v int64) *CollaborationSyncRequestUpdateOne {
	_u.mutation.ResetSnapshotVersion()
	_u.mutation.SetSnapshotVersion(v)
	return _u
}

// SetNillableSnapshotVersion sets the "snapshot_version" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableSnapshotVersion(v *int64) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetSnapshotVersion(*v)
	}
	return _u
}

// AddSnapshotVersion adds value to the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdateOne) AddSnapshotVersion(v int64) *CollaborationSyncRequestUpdateOne {
	_u.mutation.AddSnapshotVersion(v)
	return _u
}

// ClearSnapshotVersion clears the value of the "snapshot_version" field.
func (_u *CollaborationSyncRequestUpdateOne) ClearSnapshotVersion() *CollaborationSyncRequestUpdateOne {
	_u.mutation.ClearSnapshotVersion()
	return _u
}

// SetResultCount sets the "result_count" field.
func (_u *CollaborationSyncRequestUpdateOne) SetResultCount(v int) *CollaborationSyncRequestUpdateOne {
	_u.mutation.ResetResultCount()
	_u.mutation.SetResultCount(v)
	return _u
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableResultCount(v *int) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetResultCount(*v)
	}
	return _u
}

// AddResultCount adds value to the "result_count" field.
func (_u *CollaborationSyncRequestUpdateOne) AddResultCount(v int) *CollaborationSyncRequestUpdateOne {
	_u.mutation.AddResultCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CollaborationSyncRequestUpdateOne) SetExpiresAt(v time.Time) *CollaborationSyncRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CollaborationSyncRequestUpdateOne) SetCompletedAt(v time.Time) *CollaborationSyncRequestUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CollaborationSyncRequestUpdateOne) SetNillableCompletedAt(v *time.Time) *CollaborationSyncRequestUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CollaborationSyncRequestUpdateOne) ClearCompletedAt() *CollaborationSyncRequestUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the CollaborationSyncRequestMutation object of the builder.
func (_u *CollaborationSyncRequestUpdateOne) Mutation() *CollaborationSyncRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the CollaborationSyncRequestUpdate builder.
func (_u *CollaborationSyncRequestUpdateOne) Where(ps ...predicate.CollaborationSyncRequest) *CollaborationSyncRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollaborationSyncRequestUpdateOne) Select(field string, fields ...string) *CollaborationSyncRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CollaborationSyncRequest entity.
func (_u *CollaborationSyncRequestUpdateOne) Save(ctx context.Context) (*CollaborationSyncRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationSyncRequestUpdateOne) SaveX(ctx context.Context) *CollaborationSyncRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollaborationSyncRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationSyncRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollaborationSyncRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collaborationsyncrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationSyncRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := collaborationsyncrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := collaborationsyncrequest.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CollaborationSyncRequest.error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationSyncRequest.user"`)
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationSyncRequest.device"`)
	}
	return nil
}

func (_u *CollaborationSyncRequestUpdateOne) sqlSave(ctx context.Context) (_node *CollaborationSyncRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationsyncrequest.Table, collaborationsyncrequest.Columns, sqlgraph.NewFieldSpec(collaborationsyncrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollaborationSyncRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collaborationsyncrequest.FieldID)
		for _, f := range fields {
			if !collaborationsyncrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collaborationsyncrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldThreadID, field.TypeString)
	}
	if _u.mutation.CursorCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldCursor, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(collaborationsyncrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(collaborationsyncrequest.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.SnapshotVersion(); ok {
		_spec.SetField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotVersion(); ok {
		_spec.AddField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if _u.mutation.SnapshotVersionCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldSnapshotVersion, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResultCount(); ok {
		_spec.SetField(collaborationsyncrequest.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultCount(); ok {
		_spec.AddField(collaborationsyncrequest.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(collaborationsyncrequest.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(collaborationsyncrequest.FieldCompletedAt, field.TypeTime)
	}
	_node = &CollaborationSyncRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationsyncrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
