// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/collaborationcharge"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CollaborationChargeUpdate is the builder for updating CollaborationCharge entities.
type CollaborationChargeUpdate struct {
	config
	hooks    []Hook
	mutation *CollaborationChargeMutation
}

// Where appends a list predicates to the CollaborationChargeUpdate builder.
func (_u *CollaborationChargeUpdate) Where(ps ...predicate.CollaborationCharge) *CollaborationChargeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the CollaborationChargeMutation object of the builder.
func (_u *CollaborationChargeUpdate) Mutation() *CollaborationChargeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollaborationChargeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationChargeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollaborationChargeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationChargeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationChargeUpdate) check() error {
	if _u.mutation.CommandCleared() && len(_u.mutation.CommandIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCharge.command"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCharge.user"`)
	}
	return nil
}

func (_u *CollaborationChargeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationcharge.Table, collaborationcharge.Columns, sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(collaborationcharge.FieldReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationcharge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollaborationChargeUpdateOne is the builder for updating a single CollaborationCharge entity.
type CollaborationChargeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollaborationChargeMutation
}

// Mutation returns the CollaborationChargeMutation object of the builder.
func (_u *CollaborationChargeUpdateOne) Mutation() *CollaborationChargeMutation {
	return _u.mutation
}

// Where appends a list predicates to the CollaborationChargeUpdate builder.
func (_u *CollaborationChargeUpdateOne) Where(ps ...predicate.CollaborationCharge) *CollaborationChargeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollaborationChargeUpdateOne) Select(field string, fields ...string) *CollaborationChargeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CollaborationCharge entity.
func (_u *CollaborationChargeUpdateOne) Save(ctx context.Context) (*CollaborationCharge, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollaborationChargeUpdateOne) SaveX(ctx context.Context) *CollaborationCharge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollaborationChargeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollaborationChargeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollaborationChargeUpdateOne) check() error {
	if _u.mutation.CommandCleared() && len(_u.mutation.CommandIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCharge.command"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollaborationCharge.user"`)
	}
	return nil
}

func (_u *CollaborationChargeUpdateOne) sqlSave(ctx context.Context) (_node *CollaborationCharge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collaborationcharge.Table, collaborationcharge.Columns, sqlgraph.NewFieldSpec(collaborationcharge.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollaborationCharge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collaborationcharge.FieldID)
		for _, f := range fields {
			if !collaborationcharge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collaborationcharge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(collaborationcharge.FieldReason, field.TypeString)
	}
	_node = &CollaborationCharge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collaborationcharge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
