// Code generated by ent, DO NOT EDIT.

package collaborationcommand

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldDeviceID, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldThreadID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldIdempotencyKey, v))
}

// PromptSha256 applies equality check predicate on the "prompt_sha256" field. It's identical to PromptSha256EQ.
func PromptSha256(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldPromptSha256, v))
}

// PromptBytes applies equality check predicate on the "prompt_bytes" field. It's identical to PromptBytesEQ.
func PromptBytes(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldPromptBytes, v))
}

// TurnID applies equality check predicate on the "turn_id" field. It's identical to TurnIDEQ.
func TurnID(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldTurnID, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldErrorCode, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldExpiresAt, v))
}

// DispatchedAt applies equality check predicate on the "dispatched_at" field. It's identical to DispatchedAtEQ.
func DispatchedAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldDispatchedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldUserID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldDeviceID, vs...))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContainsFold(FieldThreadID, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v uuid.UUID) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldIdempotencyKey, v))
}

// PromptSha256EQ applies the EQ predicate on the "prompt_sha256" field.
func PromptSha256EQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldPromptSha256, v))
}

// PromptSha256NEQ applies the NEQ predicate on the "prompt_sha256" field.
func PromptSha256NEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldPromptSha256, v))
}

// PromptSha256In applies the In predicate on the "prompt_sha256" field.
func PromptSha256In(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldPromptSha256, vs...))
}

// PromptSha256NotIn applies the NotIn predicate on the "prompt_sha256" field.
func PromptSha256NotIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldPromptSha256, vs...))
}

// PromptSha256GT applies the GT predicate on the "prompt_sha256" field.
func PromptSha256GT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldPromptSha256, v))
}

// PromptSha256GTE applies the GTE predicate on the "prompt_sha256" field.
func PromptSha256GTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldPromptSha256, v))
}

// PromptSha256LT applies the LT predicate on the "prompt_sha256" field.
func PromptSha256LT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldPromptSha256, v))
}

// PromptSha256LTE applies the LTE predicate on the "prompt_sha256" field.
func PromptSha256LTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldPromptSha256, v))
}

// PromptSha256Contains applies the Contains predicate on the "prompt_sha256" field.
func PromptSha256Contains(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContains(FieldPromptSha256, v))
}

// PromptSha256HasPrefix applies the HasPrefix predicate on the "prompt_sha256" field.
func PromptSha256HasPrefix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasPrefix(FieldPromptSha256, v))
}

// PromptSha256HasSuffix applies the HasSuffix predicate on the "prompt_sha256" field.
func PromptSha256HasSuffix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasSuffix(FieldPromptSha256, v))
}

// PromptSha256EqualFold applies the EqualFold predicate on the "prompt_sha256" field.
func PromptSha256EqualFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEqualFold(FieldPromptSha256, v))
}

// PromptSha256ContainsFold applies the ContainsFold predicate on the "prompt_sha256" field.
func PromptSha256ContainsFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContainsFold(FieldPromptSha256, v))
}

// PromptBytesEQ applies the EQ predicate on the "prompt_bytes" field.
func PromptBytesEQ(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldPromptBytes, v))
}

// PromptBytesNEQ applies the NEQ predicate on the "prompt_bytes" field.
func PromptBytesNEQ(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldPromptBytes, v))
}

// PromptBytesIn applies the In predicate on the "prompt_bytes" field.
func PromptBytesIn(vs ...int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldPromptBytes, vs...))
}

// PromptBytesNotIn applies the NotIn predicate on the "prompt_bytes" field.
func PromptBytesNotIn(vs ...int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldPromptBytes, vs...))
}

// PromptBytesGT applies the GT predicate on the "prompt_bytes" field.
func PromptBytesGT(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldPromptBytes, v))
}

// PromptBytesGTE applies the GTE predicate on the "prompt_bytes" field.
func PromptBytesGTE(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldPromptBytes, v))
}

// PromptBytesLT applies the LT predicate on the "prompt_bytes" field.
func PromptBytesLT(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldPromptBytes, v))
}

// PromptBytesLTE applies the LTE predicate on the "prompt_bytes" field.
func PromptBytesLTE(v int) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldPromptBytes, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldStatus, vs...))
}

// TurnIDEQ applies the EQ predicate on the "turn_id" field.
func TurnIDEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldTurnID, v))
}

// TurnIDNEQ applies the NEQ predicate on the "turn_id" field.
func TurnIDNEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldTurnID, v))
}

// TurnIDIn applies the In predicate on the "turn_id" field.
func TurnIDIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldTurnID, vs...))
}

// TurnIDNotIn applies the NotIn predicate on the "turn_id" field.
func TurnIDNotIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldTurnID, vs...))
}

// TurnIDGT applies the GT predicate on the "turn_id" field.
func TurnIDGT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldTurnID, v))
}

// TurnIDGTE applies the GTE predicate on the "turn_id" field.
func TurnIDGTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldTurnID, v))
}

// TurnIDLT applies the LT predicate on the "turn_id" field.
func TurnIDLT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldTurnID, v))
}

// TurnIDLTE applies the LTE predicate on the "turn_id" field.
func TurnIDLTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldTurnID, v))
}

// TurnIDContains applies the Contains predicate on the "turn_id" field.
func TurnIDContains(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContains(FieldTurnID, v))
}

// TurnIDHasPrefix applies the HasPrefix predicate on the "turn_id" field.
func TurnIDHasPrefix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasPrefix(FieldTurnID, v))
}

// TurnIDHasSuffix applies the HasSuffix predicate on the "turn_id" field.
func TurnIDHasSuffix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasSuffix(FieldTurnID, v))
}

// TurnIDIsNil applies the IsNil predicate on the "turn_id" field.
func TurnIDIsNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIsNull(FieldTurnID))
}

// TurnIDNotNil applies the NotNil predicate on the "turn_id" field.
func TurnIDNotNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotNull(FieldTurnID))
}

// TurnIDEqualFold applies the EqualFold predicate on the "turn_id" field.
func TurnIDEqualFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEqualFold(FieldTurnID, v))
}

// TurnIDContainsFold applies the ContainsFold predicate on the "turn_id" field.
func TurnIDContainsFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContainsFold(FieldTurnID, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldContainsFold(FieldErrorCode, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldExpiresAt, v))
}

// DispatchedAtEQ applies the EQ predicate on the "dispatched_at" field.
func DispatchedAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldDispatchedAt, v))
}

// DispatchedAtNEQ applies the NEQ predicate on the "dispatched_at" field.
func DispatchedAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldDispatchedAt, v))
}

// DispatchedAtIn applies the In predicate on the "dispatched_at" field.
func DispatchedAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldDispatchedAt, vs...))
}

// DispatchedAtNotIn applies the NotIn predicate on the "dispatched_at" field.
func DispatchedAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldDispatchedAt, vs...))
}

// DispatchedAtGT applies the GT predicate on the "dispatched_at" field.
func DispatchedAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldDispatchedAt, v))
}

// DispatchedAtGTE applies the GTE predicate on the "dispatched_at" field.
func DispatchedAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldDispatchedAt, v))
}

// DispatchedAtLT applies the LT predicate on the "dispatched_at" field.
func DispatchedAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldDispatchedAt, v))
}

// DispatchedAtLTE applies the LTE predicate on the "dispatched_at" field.
func DispatchedAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldDispatchedAt, v))
}

// DispatchedAtIsNil applies the IsNil predicate on the "dispatched_at" field.
func DispatchedAtIsNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIsNull(FieldDispatchedAt))
}

// DispatchedAtNotNil applies the NotNil predicate on the "dispatched_at" field.
func DispatchedAtNotNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotNull(FieldDispatchedAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.FieldNotNull(FieldCompletedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.CollaborationDevice) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCharge applies the HasEdge predicate on the "charge" edge.
func HasCharge() predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ChargeTable, ChargeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChargeWith applies the HasEdge predicate on the "charge" edge with a given conditions (other predicates).
func HasChargeWith(preds ...predicate.CollaborationCharge) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(func(s *sql.Selector) {
		step := newChargeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CollaborationCommand) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CollaborationCommand) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CollaborationCommand) predicate.CollaborationCommand {
	return predicate.CollaborationCommand(sql.NotPredicates(p))
}
