// Code generated by ent, DO NOT EDIT.

package collaborationcharge

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the collaborationcharge type in the database.
	Label = "collaboration_charge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCommandID holds the string denoting the command_id field in the database.
	FieldCommandID = "command_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldChargedAt holds the string denoting the charged_at field in the database.
	FieldChargedAt = "charged_at"
	// EdgeCommand holds the string denoting the command edge name in mutations.
	EdgeCommand = "command"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the collaborationcharge in the database.
	Table = "collaboration_charges"
	// CommandTable is the table that holds the command relation/edge.
	CommandTable = "collaboration_charges"
	// CommandInverseTable is the table name for the CollaborationCommand entity.
	// It exists in this package in order to avoid circular dependency with the "collaborationcommand" package.
	CommandInverseTable = "collaboration_commands"
	// CommandColumn is the table column denoting the command relation/edge.
	CommandColumn = "command_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "collaboration_charges"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for collaborationcharge fields.
var Columns = []string{
	FieldID,
	FieldCommandID,
	FieldUserID,
	FieldAmount,
	FieldCurrency,
	FieldStatus,
	FieldBalanceBefore,
	FieldBalanceAfter,
	FieldReason,
	FieldChargedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultChargedAt holds the default value on creation for the "charged_at" field.
	DefaultChargedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusCharged is the default value of the Status enum.
const DefaultStatus = StatusCharged

// Status values.
const (
	StatusCharged Status = "charged"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCharged:
		return nil
	default:
		return fmt.Errorf("collaborationcharge: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the CollaborationCharge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCommandID orders the results by the command_id field.
func ByCommandID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommandID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByChargedAt orders the results by the charged_at field.
func ByChargedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargedAt, opts...).ToFunc()
}

// ByCommandField orders the results by command field.
func ByCommandField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommandStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newCommandStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommandInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, CommandTable, CommandColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
