// Code generated by ent, DO NOT EDIT.

package collaborationcharge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldID, id))
}

// CommandID applies equality check predicate on the "command_id" field. It's identical to CommandIDEQ.
func CommandID(v uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldCommandID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldCurrency, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldBalanceAfter, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldReason, v))
}

// ChargedAt applies equality check predicate on the "charged_at" field. It's identical to ChargedAtEQ.
func ChargedAt(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldChargedAt, v))
}

// CommandIDEQ applies the EQ predicate on the "command_id" field.
func CommandIDEQ(v uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldCommandID, v))
}

// CommandIDNEQ applies the NEQ predicate on the "command_id" field.
func CommandIDNEQ(v uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldCommandID, v))
}

// CommandIDIn applies the In predicate on the "command_id" field.
func CommandIDIn(vs ...uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldCommandID, vs...))
}

// CommandIDNotIn applies the NotIn predicate on the "command_id" field.
func CommandIDNotIn(vs ...uuid.UUID) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldCommandID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContainsFold(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldStatus, vs...))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceBeforeContains applies the Contains predicate on the "balance_before" field.
func BalanceBeforeContains(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContains(FieldBalanceBefore, v))
}

// BalanceBeforeHasPrefix applies the HasPrefix predicate on the "balance_before" field.
func BalanceBeforeHasPrefix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasPrefix(FieldBalanceBefore, v))
}

// BalanceBeforeHasSuffix applies the HasSuffix predicate on the "balance_before" field.
func BalanceBeforeHasSuffix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasSuffix(FieldBalanceBefore, v))
}

// BalanceBeforeEqualFold applies the EqualFold predicate on the "balance_before" field.
func BalanceBeforeEqualFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEqualFold(FieldBalanceBefore, v))
}

// BalanceBeforeContainsFold applies the ContainsFold predicate on the "balance_before" field.
func BalanceBeforeContainsFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContainsFold(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterContains applies the Contains predicate on the "balance_after" field.
func BalanceAfterContains(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContains(FieldBalanceAfter, v))
}

// BalanceAfterHasPrefix applies the HasPrefix predicate on the "balance_after" field.
func BalanceAfterHasPrefix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasPrefix(FieldBalanceAfter, v))
}

// BalanceAfterHasSuffix applies the HasSuffix predicate on the "balance_after" field.
func BalanceAfterHasSuffix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasSuffix(FieldBalanceAfter, v))
}

// BalanceAfterEqualFold applies the EqualFold predicate on the "balance_after" field.
func BalanceAfterEqualFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEqualFold(FieldBalanceAfter, v))
}

// BalanceAfterContainsFold applies the ContainsFold predicate on the "balance_after" field.
func BalanceAfterContainsFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContainsFold(FieldBalanceAfter, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldContainsFold(FieldReason, v))
}

// ChargedAtEQ applies the EQ predicate on the "charged_at" field.
func ChargedAtEQ(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldEQ(FieldChargedAt, v))
}

// ChargedAtNEQ applies the NEQ predicate on the "charged_at" field.
func ChargedAtNEQ(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNEQ(FieldChargedAt, v))
}

// ChargedAtIn applies the In predicate on the "charged_at" field.
func ChargedAtIn(vs ...time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldIn(FieldChargedAt, vs...))
}

// ChargedAtNotIn applies the NotIn predicate on the "charged_at" field.
func ChargedAtNotIn(vs ...time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldNotIn(FieldChargedAt, vs...))
}

// ChargedAtGT applies the GT predicate on the "charged_at" field.
func ChargedAtGT(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGT(FieldChargedAt, v))
}

// ChargedAtGTE applies the GTE predicate on the "charged_at" field.
func ChargedAtGTE(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldGTE(FieldChargedAt, v))
}

// ChargedAtLT applies the LT predicate on the "charged_at" field.
func ChargedAtLT(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLT(FieldChargedAt, v))
}

// ChargedAtLTE applies the LTE predicate on the "charged_at" field.
func ChargedAtLTE(v time.Time) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.FieldLTE(FieldChargedAt, v))
}

// HasCommand applies the HasEdge predicate on the "command" edge.
func HasCommand() predicate.CollaborationCharge {
	return predicate.CollaborationCharge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, CommandTable, CommandColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommandWith applies the HasEdge predicate on the "command" edge with a given conditions (other predicates).
func HasCommandWith(preds ...predicate.CollaborationCommand) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(func(s *sql.Selector) {
		step := newCommandStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CollaborationCharge {
	return predicate.CollaborationCharge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CollaborationCharge) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CollaborationCharge) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CollaborationCharge) predicate.CollaborationCharge {
	return predicate.CollaborationCharge(sql.NotPredicates(p))
}
