// Code generated by ent, DO NOT EDIT.

package collaborationsyncrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldDeviceID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldIdempotencyKey, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldThreadID, v))
}

// Cursor applies equality check predicate on the "cursor" field. It's identical to CursorEQ.
func Cursor(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCursor, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldErrorCode, v))
}

// SnapshotVersion applies equality check predicate on the "snapshot_version" field. It's identical to SnapshotVersionEQ.
func SnapshotVersion(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldSnapshotVersion, v))
}

// ResultCount applies equality check predicate on the "result_count" field. It's identical to ResultCountEQ.
func ResultCount(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldResultCount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldDeviceID, vs...))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v uuid.UUID) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldIdempotencyKey, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldKind, vs...))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDIsNil applies the IsNil predicate on the "thread_id" field.
func ThreadIDIsNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIsNull(FieldThreadID))
}

// ThreadIDNotNil applies the NotNil predicate on the "thread_id" field.
func ThreadIDNotNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotNull(FieldThreadID))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContainsFold(FieldThreadID, v))
}

// CursorEQ applies the EQ predicate on the "cursor" field.
func CursorEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCursor, v))
}

// CursorNEQ applies the NEQ predicate on the "cursor" field.
func CursorNEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldCursor, v))
}

// CursorIn applies the In predicate on the "cursor" field.
func CursorIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldCursor, vs...))
}

// CursorNotIn applies the NotIn predicate on the "cursor" field.
func CursorNotIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldCursor, vs...))
}

// CursorGT applies the GT predicate on the "cursor" field.
func CursorGT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldCursor, v))
}

// CursorGTE applies the GTE predicate on the "cursor" field.
func CursorGTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldCursor, v))
}

// CursorLT applies the LT predicate on the "cursor" field.
func CursorLT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldCursor, v))
}

// CursorLTE applies the LTE predicate on the "cursor" field.
func CursorLTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldCursor, v))
}

// CursorContains applies the Contains predicate on the "cursor" field.
func CursorContains(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContains(FieldCursor, v))
}

// CursorHasPrefix applies the HasPrefix predicate on the "cursor" field.
func CursorHasPrefix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasPrefix(FieldCursor, v))
}

// CursorHasSuffix applies the HasSuffix predicate on the "cursor" field.
func CursorHasSuffix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasSuffix(FieldCursor, v))
}

// CursorIsNil applies the IsNil predicate on the "cursor" field.
func CursorIsNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIsNull(FieldCursor))
}

// CursorNotNil applies the NotNil predicate on the "cursor" field.
func CursorNotNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotNull(FieldCursor))
}

// CursorEqualFold applies the EqualFold predicate on the "cursor" field.
func CursorEqualFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEqualFold(FieldCursor, v))
}

// CursorContainsFold applies the ContainsFold predicate on the "cursor" field.
func CursorContainsFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContainsFold(FieldCursor, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldContainsFold(FieldErrorCode, v))
}

// SnapshotVersionEQ applies the EQ predicate on the "snapshot_version" field.
func SnapshotVersionEQ(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldSnapshotVersion, v))
}

// SnapshotVersionNEQ applies the NEQ predicate on the "snapshot_version" field.
func SnapshotVersionNEQ(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldSnapshotVersion, v))
}

// SnapshotVersionIn applies the In predicate on the "snapshot_version" field.
func SnapshotVersionIn(vs ...int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldSnapshotVersion, vs...))
}

// SnapshotVersionNotIn applies the NotIn predicate on the "snapshot_version" field.
func SnapshotVersionNotIn(vs ...int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldSnapshotVersion, vs...))
}

// SnapshotVersionGT applies the GT predicate on the "snapshot_version" field.
func SnapshotVersionGT(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldSnapshotVersion, v))
}

// SnapshotVersionGTE applies the GTE predicate on the "snapshot_version" field.
func SnapshotVersionGTE(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldSnapshotVersion, v))
}

// SnapshotVersionLT applies the LT predicate on the "snapshot_version" field.
func SnapshotVersionLT(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldSnapshotVersion, v))
}

// SnapshotVersionLTE applies the LTE predicate on the "snapshot_version" field.
func SnapshotVersionLTE(v int64) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldSnapshotVersion, v))
}

// SnapshotVersionIsNil applies the IsNil predicate on the "snapshot_version" field.
func SnapshotVersionIsNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIsNull(FieldSnapshotVersion))
}

// SnapshotVersionNotNil applies the NotNil predicate on the "snapshot_version" field.
func SnapshotVersionNotNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotNull(FieldSnapshotVersion))
}

// ResultCountEQ applies the EQ predicate on the "result_count" field.
func ResultCountEQ(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldResultCount, v))
}

// ResultCountNEQ applies the NEQ predicate on the "result_count" field.
func ResultCountNEQ(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldResultCount, v))
}

// ResultCountIn applies the In predicate on the "result_count" field.
func ResultCountIn(vs ...int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldResultCount, vs...))
}

// ResultCountNotIn applies the NotIn predicate on the "result_count" field.
func ResultCountNotIn(vs ...int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldResultCount, vs...))
}

// ResultCountGT applies the GT predicate on the "result_count" field.
func ResultCountGT(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldResultCount, v))
}

// ResultCountGTE applies the GTE predicate on the "result_count" field.
func ResultCountGTE(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldResultCount, v))
}

// ResultCountLT applies the LT predicate on the "result_count" field.
func ResultCountLT(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldResultCount, v))
}

// ResultCountLTE applies the LTE predicate on the "result_count" field.
func ResultCountLTE(v int) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldResultCount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldExpiresAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.FieldNotNull(FieldCompletedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.CollaborationDevice) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CollaborationSyncRequest) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CollaborationSyncRequest) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CollaborationSyncRequest) predicate.CollaborationSyncRequest {
	return predicate.CollaborationSyncRequest(sql.NotPredicates(p))
}
