// Code generated by ent, DO NOT EDIT.

package collaborationdevice

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the collaborationdevice type in the database.
	Label = "collaboration_device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldInstallationIDHash holds the string denoting the installation_id_hash field in the database.
	FieldInstallationIDHash = "installation_id_hash"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformVersion holds the string denoting the platform_version field in the database.
	FieldPlatformVersion = "platform_version"
	// FieldCompanionVersion holds the string denoting the companion_version field in the database.
	FieldCompanionVersion = "companion_version"
	// FieldCodexVersion holds the string denoting the codex_version field in the database.
	FieldCodexVersion = "codex_version"
	// FieldProtocolVersion holds the string denoting the protocol_version field in the database.
	FieldProtocolVersion = "protocol_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSyncRequests holds the string denoting the sync_requests edge name in mutations.
	EdgeSyncRequests = "sync_requests"
	// EdgeCommands holds the string denoting the commands edge name in mutations.
	EdgeCommands = "commands"
	// Table holds the table name of the collaborationdevice in the database.
	Table = "collaboration_devices"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "collaboration_devices"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SyncRequestsTable is the table that holds the sync_requests relation/edge.
	SyncRequestsTable = "collaboration_sync_requests"
	// SyncRequestsInverseTable is the table name for the CollaborationSyncRequest entity.
	// It exists in this package in order to avoid circular dependency with the "collaborationsyncrequest" package.
	SyncRequestsInverseTable = "collaboration_sync_requests"
	// SyncRequestsColumn is the table column denoting the sync_requests relation/edge.
	SyncRequestsColumn = "device_id"
	// CommandsTable is the table that holds the commands relation/edge.
	CommandsTable = "collaboration_commands"
	// CommandsInverseTable is the table name for the CollaborationCommand entity.
	// It exists in this package in order to avoid circular dependency with the "collaborationcommand" package.
	CommandsInverseTable = "collaboration_commands"
	// CommandsColumn is the table column denoting the commands relation/edge.
	CommandsColumn = "device_id"
)

// Columns holds all SQL columns for collaborationdevice fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldInstallationIDHash,
	FieldName,
	FieldPlatform,
	FieldPlatformVersion,
	FieldCompanionVersion,
	FieldCodexVersion,
	FieldProtocolVersion,
	FieldStatus,
	FieldCapabilities,
	FieldLastSeenAt,
	FieldRevokedAt,
	FieldRegisteredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// InstallationIDHashValidator is a validator for the "installation_id_hash" field. It is called by the builders before save.
	InstallationIDHashValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformVersionValidator is a validator for the "platform_version" field. It is called by the builders before save.
	PlatformVersionValidator func(string) error
	// CompanionVersionValidator is a validator for the "companion_version" field. It is called by the builders before save.
	CompanionVersionValidator func(string) error
	// CodexVersionValidator is a validator for the "codex_version" field. It is called by the builders before save.
	CodexVersionValidator func(string) error
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities func() map[string]interface{}
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Platform defines the type for the "platform" enum field.
type Platform string

// Platform values.
const (
	PlatformWindows Platform = "windows"
	PlatformMacos   Platform = "macos"
	PlatformLinux   Platform = "linux"
)

func (pl Platform) String() string {
	return string(pl)
}

// PlatformValidator is a validator for the "platform" field enum values. It is called by the builders before save.
func PlatformValidator(pl Platform) error {
	switch pl {
	case PlatformWindows, PlatformMacos, PlatformLinux:
		return nil
	default:
		return fmt.Errorf("collaborationdevice: invalid enum value for platform field: %q", pl)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusOffline is the default value of the Status enum.
const DefaultStatus = StatusOffline

// Status values.
const (
	StatusOffline  Status = "offline"
	StatusOnline   Status = "online"
	StatusDegraded Status = "degraded"
	StatusRevoked  Status = "revoked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusOffline, StatusOnline, StatusDegraded, StatusRevoked:
		return nil
	default:
		return fmt.Errorf("collaborationdevice: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the CollaborationDevice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByInstallationIDHash orders the results by the installation_id_hash field.
func ByInstallationIDHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationIDHash, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformVersion orders the results by the platform_version field.
func ByPlatformVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformVersion, opts...).ToFunc()
}

// ByCompanionVersion orders the results by the companion_version field.
func ByCompanionVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanionVersion, opts...).ToFunc()
}

// ByCodexVersion orders the results by the codex_version field.
func ByCodexVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexVersion, opts...).ToFunc()
}

// ByProtocolVersion orders the results by the protocol_version field.
func ByProtocolVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocolVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySyncRequestsCount orders the results by sync_requests count.
func BySyncRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSyncRequestsStep(), opts...)
	}
}

// BySyncRequests orders the results by sync_requests terms.
func BySyncRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSyncRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommandsCount orders the results by commands count.
func ByCommandsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommandsStep(), opts...)
	}
}

// ByCommands orders the results by commands terms.
func ByCommands(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommandsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSyncRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SyncRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SyncRequestsTable, SyncRequestsColumn),
	)
}
func newCommandsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommandsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommandsTable, CommandsColumn),
	)
}
