// Code generated by ent, DO NOT EDIT.

package collaborationdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldUserID, v))
}

// InstallationIDHash applies equality check predicate on the "installation_id_hash" field. It's identical to InstallationIDHashEQ.
func InstallationIDHash(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldInstallationIDHash, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldName, v))
}

// PlatformVersion applies equality check predicate on the "platform_version" field. It's identical to PlatformVersionEQ.
func PlatformVersion(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldPlatformVersion, v))
}

// CompanionVersion applies equality check predicate on the "companion_version" field. It's identical to CompanionVersionEQ.
func CompanionVersion(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCompanionVersion, v))
}

// CodexVersion applies equality check predicate on the "codex_version" field. It's identical to CodexVersionEQ.
func CodexVersion(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCodexVersion, v))
}

// ProtocolVersion applies equality check predicate on the "protocol_version" field. It's identical to ProtocolVersionEQ.
func ProtocolVersion(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldProtocolVersion, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// RegisteredAt applies equality check predicate on the "registered_at" field. It's identical to RegisteredAtEQ.
func RegisteredAt(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldRegisteredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldUserID, vs...))
}

// InstallationIDHashEQ applies the EQ predicate on the "installation_id_hash" field.
func InstallationIDHashEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashNEQ applies the NEQ predicate on the "installation_id_hash" field.
func InstallationIDHashNEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashIn applies the In predicate on the "installation_id_hash" field.
func InstallationIDHashIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashNotIn applies the NotIn predicate on the "installation_id_hash" field.
func InstallationIDHashNotIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashGT applies the GT predicate on the "installation_id_hash" field.
func InstallationIDHashGT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldInstallationIDHash, v))
}

// InstallationIDHashGTE applies the GTE predicate on the "installation_id_hash" field.
func InstallationIDHashGTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldInstallationIDHash, v))
}

// InstallationIDHashLT applies the LT predicate on the "installation_id_hash" field.
func InstallationIDHashLT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldInstallationIDHash, v))
}

// InstallationIDHashLTE applies the LTE predicate on the "installation_id_hash" field.
func InstallationIDHashLTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldInstallationIDHash, v))
}

// InstallationIDHashContains applies the Contains predicate on the "installation_id_hash" field.
func InstallationIDHashContains(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContains(FieldInstallationIDHash, v))
}

// InstallationIDHashHasPrefix applies the HasPrefix predicate on the "installation_id_hash" field.
func InstallationIDHashHasPrefix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasPrefix(FieldInstallationIDHash, v))
}

// InstallationIDHashHasSuffix applies the HasSuffix predicate on the "installation_id_hash" field.
func InstallationIDHashHasSuffix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasSuffix(FieldInstallationIDHash, v))
}

// InstallationIDHashEqualFold applies the EqualFold predicate on the "installation_id_hash" field.
func InstallationIDHashEqualFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEqualFold(FieldInstallationIDHash, v))
}

// InstallationIDHashContainsFold applies the ContainsFold predicate on the "installation_id_hash" field.
func InstallationIDHashContainsFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContainsFold(FieldInstallationIDHash, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v Platform) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v Platform) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...Platform) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...Platform) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformVersionEQ applies the EQ predicate on the "platform_version" field.
func PlatformVersionEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldPlatformVersion, v))
}

// PlatformVersionNEQ applies the NEQ predicate on the "platform_version" field.
func PlatformVersionNEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldPlatformVersion, v))
}

// PlatformVersionIn applies the In predicate on the "platform_version" field.
func PlatformVersionIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldPlatformVersion, vs...))
}

// PlatformVersionNotIn applies the NotIn predicate on the "platform_version" field.
func PlatformVersionNotIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldPlatformVersion, vs...))
}

// PlatformVersionGT applies the GT predicate on the "platform_version" field.
func PlatformVersionGT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldPlatformVersion, v))
}

// PlatformVersionGTE applies the GTE predicate on the "platform_version" field.
func PlatformVersionGTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldPlatformVersion, v))
}

// PlatformVersionLT applies the LT predicate on the "platform_version" field.
func PlatformVersionLT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldPlatformVersion, v))
}

// PlatformVersionLTE applies the LTE predicate on the "platform_version" field.
func PlatformVersionLTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldPlatformVersion, v))
}

// PlatformVersionContains applies the Contains predicate on the "platform_version" field.
func PlatformVersionContains(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContains(FieldPlatformVersion, v))
}

// PlatformVersionHasPrefix applies the HasPrefix predicate on the "platform_version" field.
func PlatformVersionHasPrefix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasPrefix(FieldPlatformVersion, v))
}

// PlatformVersionHasSuffix applies the HasSuffix predicate on the "platform_version" field.
func PlatformVersionHasSuffix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasSuffix(FieldPlatformVersion, v))
}

// PlatformVersionIsNil applies the IsNil predicate on the "platform_version" field.
func PlatformVersionIsNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIsNull(FieldPlatformVersion))
}

// PlatformVersionNotNil applies the NotNil predicate on the "platform_version" field.
func PlatformVersionNotNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotNull(FieldPlatformVersion))
}

// PlatformVersionEqualFold applies the EqualFold predicate on the "platform_version" field.
func PlatformVersionEqualFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEqualFold(FieldPlatformVersion, v))
}

// PlatformVersionContainsFold applies the ContainsFold predicate on the "platform_version" field.
func PlatformVersionContainsFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContainsFold(FieldPlatformVersion, v))
}

// CompanionVersionEQ applies the EQ predicate on the "companion_version" field.
func CompanionVersionEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCompanionVersion, v))
}

// CompanionVersionNEQ applies the NEQ predicate on the "companion_version" field.
func CompanionVersionNEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldCompanionVersion, v))
}

// CompanionVersionIn applies the In predicate on the "companion_version" field.
func CompanionVersionIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldCompanionVersion, vs...))
}

// CompanionVersionNotIn applies the NotIn predicate on the "companion_version" field.
func CompanionVersionNotIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldCompanionVersion, vs...))
}

// CompanionVersionGT applies the GT predicate on the "companion_version" field.
func CompanionVersionGT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldCompanionVersion, v))
}

// CompanionVersionGTE applies the GTE predicate on the "companion_version" field.
func CompanionVersionGTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldCompanionVersion, v))
}

// CompanionVersionLT applies the LT predicate on the "companion_version" field.
func CompanionVersionLT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldCompanionVersion, v))
}

// CompanionVersionLTE applies the LTE predicate on the "companion_version" field.
func CompanionVersionLTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldCompanionVersion, v))
}

// CompanionVersionContains applies the Contains predicate on the "companion_version" field.
func CompanionVersionContains(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContains(FieldCompanionVersion, v))
}

// CompanionVersionHasPrefix applies the HasPrefix predicate on the "companion_version" field.
func CompanionVersionHasPrefix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasPrefix(FieldCompanionVersion, v))
}

// CompanionVersionHasSuffix applies the HasSuffix predicate on the "companion_version" field.
func CompanionVersionHasSuffix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasSuffix(FieldCompanionVersion, v))
}

// CompanionVersionEqualFold applies the EqualFold predicate on the "companion_version" field.
func CompanionVersionEqualFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEqualFold(FieldCompanionVersion, v))
}

// CompanionVersionContainsFold applies the ContainsFold predicate on the "companion_version" field.
func CompanionVersionContainsFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContainsFold(FieldCompanionVersion, v))
}

// CodexVersionEQ applies the EQ predicate on the "codex_version" field.
func CodexVersionEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldCodexVersion, v))
}

// CodexVersionNEQ applies the NEQ predicate on the "codex_version" field.
func CodexVersionNEQ(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldCodexVersion, v))
}

// CodexVersionIn applies the In predicate on the "codex_version" field.
func CodexVersionIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldCodexVersion, vs...))
}

// CodexVersionNotIn applies the NotIn predicate on the "codex_version" field.
func CodexVersionNotIn(vs ...string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldCodexVersion, vs...))
}

// CodexVersionGT applies the GT predicate on the "codex_version" field.
func CodexVersionGT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldCodexVersion, v))
}

// CodexVersionGTE applies the GTE predicate on the "codex_version" field.
func CodexVersionGTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldCodexVersion, v))
}

// CodexVersionLT applies the LT predicate on the "codex_version" field.
func CodexVersionLT(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldCodexVersion, v))
}

// CodexVersionLTE applies the LTE predicate on the "codex_version" field.
func CodexVersionLTE(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldCodexVersion, v))
}

// CodexVersionContains applies the Contains predicate on the "codex_version" field.
func CodexVersionContains(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContains(FieldCodexVersion, v))
}

// CodexVersionHasPrefix applies the HasPrefix predicate on the "codex_version" field.
func CodexVersionHasPrefix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasPrefix(FieldCodexVersion, v))
}

// CodexVersionHasSuffix applies the HasSuffix predicate on the "codex_version" field.
func CodexVersionHasSuffix(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldHasSuffix(FieldCodexVersion, v))
}

// CodexVersionIsNil applies the IsNil predicate on the "codex_version" field.
func CodexVersionIsNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIsNull(FieldCodexVersion))
}

// CodexVersionNotNil applies the NotNil predicate on the "codex_version" field.
func CodexVersionNotNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotNull(FieldCodexVersion))
}

// CodexVersionEqualFold applies the EqualFold predicate on the "codex_version" field.
func CodexVersionEqualFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEqualFold(FieldCodexVersion, v))
}

// CodexVersionContainsFold applies the ContainsFold predicate on the "codex_version" field.
func CodexVersionContainsFold(v string) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldContainsFold(FieldCodexVersion, v))
}

// ProtocolVersionEQ applies the EQ predicate on the "protocol_version" field.
func ProtocolVersionEQ(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldProtocolVersion, v))
}

// ProtocolVersionNEQ applies the NEQ predicate on the "protocol_version" field.
func ProtocolVersionNEQ(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldProtocolVersion, v))
}

// ProtocolVersionIn applies the In predicate on the "protocol_version" field.
func ProtocolVersionIn(vs ...int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionNotIn applies the NotIn predicate on the "protocol_version" field.
func ProtocolVersionNotIn(vs ...int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldProtocolVersion, vs...))
}

// ProtocolVersionGT applies the GT predicate on the "protocol_version" field.
func ProtocolVersionGT(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldProtocolVersion, v))
}

// ProtocolVersionGTE applies the GTE predicate on the "protocol_version" field.
func ProtocolVersionGTE(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldProtocolVersion, v))
}

// ProtocolVersionLT applies the LT predicate on the "protocol_version" field.
func ProtocolVersionLT(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldProtocolVersion, v))
}

// ProtocolVersionLTE applies the LTE predicate on the "protocol_version" field.
func ProtocolVersionLTE(v int) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldProtocolVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldStatus, vs...))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotNull(FieldLastSeenAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotNull(FieldRevokedAt))
}

// RegisteredAtEQ applies the EQ predicate on the "registered_at" field.
func RegisteredAtEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldEQ(FieldRegisteredAt, v))
}

// RegisteredAtNEQ applies the NEQ predicate on the "registered_at" field.
func RegisteredAtNEQ(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNEQ(FieldRegisteredAt, v))
}

// RegisteredAtIn applies the In predicate on the "registered_at" field.
func RegisteredAtIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldIn(FieldRegisteredAt, vs...))
}

// RegisteredAtNotIn applies the NotIn predicate on the "registered_at" field.
func RegisteredAtNotIn(vs ...time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldNotIn(FieldRegisteredAt, vs...))
}

// RegisteredAtGT applies the GT predicate on the "registered_at" field.
func RegisteredAtGT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGT(FieldRegisteredAt, v))
}

// RegisteredAtGTE applies the GTE predicate on the "registered_at" field.
func RegisteredAtGTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldGTE(FieldRegisteredAt, v))
}

// RegisteredAtLT applies the LT predicate on the "registered_at" field.
func RegisteredAtLT(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLT(FieldRegisteredAt, v))
}

// RegisteredAtLTE applies the LTE predicate on the "registered_at" field.
func RegisteredAtLTE(v time.Time) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.FieldLTE(FieldRegisteredAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyncRequests applies the HasEdge predicate on the "sync_requests" edge.
func HasSyncRequests() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncRequestsTable, SyncRequestsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncRequestsWith applies the HasEdge predicate on the "sync_requests" edge with a given conditions (other predicates).
func HasSyncRequestsWith(preds ...predicate.CollaborationSyncRequest) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := newSyncRequestsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommands applies the HasEdge predicate on the "commands" edge.
func HasCommands() predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommandsTable, CommandsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommandsWith applies the HasEdge predicate on the "commands" edge with a given conditions (other predicates).
func HasCommandsWith(preds ...predicate.CollaborationCommand) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(func(s *sql.Selector) {
		step := newCommandsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CollaborationDevice) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CollaborationDevice) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CollaborationDevice) predicate.CollaborationDevice {
	return predicate.CollaborationDevice(sql.NotPredicates(p))
}
